### ISSUE TITLE
BUILD_WASI_SUPPORT for the library target?

### ISSUE THREAD

**Issue by saghul** [wasm3/wasm3#107]
Hey there!

I'm integrating wasm3 as a library in a project and I'd like to turn on WASI support. I noticed BUILD_WASI_SUPPORT was introduced recently, but it's not available in the library target. Was this deliberate? I can subit a patch if it's acceptable to have it.

PS: Integration was really simple ❤️

**Comment by vshymanskyy** [comment]
Thanks. PR would be welcome!

**Comment by saghul** [comment]
See #108
