### ISSUE TITLE
Document signature format?

### ISSUE THREAD

**Issue by onionhammer** [wasm3/wasm3#109]
Hey guys,

Trying to find some documentation for `m3_LinkRawFunction`'s signature; I would like to consume  a struct argument, but all the examples are very simple (and obvious)

```
v(i) <- void (int)
i(i) <- int (int)
v(ii) <- void (int, int)
v(**) <- void (ptr, ptr)
```

but what about other types; u16, or structs?

**Comment by vshymanskyy** [comment]
WebAssembly core only supports simple and obvious `i32`, `i64`, `f32`, `f64`.

**Comment by vshymanskyy** [comment]
@onionhammer I think the question is answered. If you need help with something specific, please join our Discord channel. And of course, you're welcome to ask more questions here ;)

**Comment by onionhammer** [comment]
@vshymanskyy That does answer that I cannot pass structs from javascript, but it does not answer the broader question on the lack of documentation for that signature format. I would say this issue should remain open until such documentation exists

**Comment by FGasper** [comment]
For anyone else who may find their way here, the format is parsed in `m3_bind.c`.

The general format is: `$RETURNS($ARGS)`

… where $RETURNS and $ARGS are both either:
- `v`, to indicate empty
- A sequence of one or more of: `i` (i32), `I` (i64), `f` (f32), `F` (f64)

Space characters are ignored.

**Comment by vshymanskyy** [comment]
Star is just a pointer.
Wasm works with offsets in the Linear Memory, so star helps translating it into the VM/Host address space.
