### ISSUE TITLE
Bug in PreserveArgsAndLocals

### ISSUE THREAD

**Issue by kgdev** [wasm3/wasm3#111]
![image](https://user-images.githubusercontent.com/6348456/75163967-0e31b300-575b-11ea-8b93-bf4076c68ff4.png)

stackIndex is the index of the current execution stack.
firstSlotIndex is the index of a slot.
They are two things and must be wrong?

This will make our program to run incorrectly.

**Comment by soundandform** [comment]
Thanks.  I think I already fixed this while working on issue #5.  It should be patched soon.

**Comment by soundandform** [comment]
@kgdev Now committed, but issue #5 worked touched a fair amount of code. I suspect I broke something else in the process! :)

**Comment by vshymanskyy** [comment]
@kgdev could you re-check this one?
