### ISSUE TITLE
Symbol clash / override

### ISSUE THREAD

**Issue by saghul** [wasm3/wasm3#112]
Hi there,

I'm currently integrating wasm3 as the WASM engine for QuickJS. Here is my work so far (in case you're curious): https://github.com/saghul/txiki.js/pull/121

It's going great so far, but when writing some tests I noticed some odd behavior I'd like to clarify. I took the spec tests and wanted to run some operations to validate the correctness of the integration but I noticed that if I use a single runtime then the last "add" function which is loaded (for example) shadows the previous ones. So, if I have some `add(i32, i32)` and then load some `add(f32, f32)` the latter will be the one used.

I resorted to having separate runtimes per WebAssembly.Instance, since that would avoid the issue, but I'm not 100% sure I'm doing the right thing here.

Any ideas would be welcome.

**Comment by vshymanskyy** [comment]
First of all. Wasm3 + QuickJS is a perfect match and I'm so glad you started working on it!..
Let me see what's going on there..
It would be exciting to get this working. I think Wasm3 may be missing a good part of APIs that are needed for this, but let's work through it.

**Comment by vshymanskyy** [comment]
@saghul I just checked this. I think you did the correct thing. You need a runtime per wasm module. Unless you want to link multiple wasm modules (which is not currently supported anyway).
I also added a new [`emscripten_lib`](https://github.com/wasm3/wasm3/tree/master/platforms/emscripten_lib) platform, which demonstrates how to expose Wasm3 API to JS (using Emscripten).

**Comment by bonifaido** [comment]
Is this still the current case? So you need one runtime per module to avoid clashes and module linking is still not supported?

**Comment by vshymanskyy** [comment]
most probably!
