### ISSUE TITLE
Accessing native memory

### ISSUE THREAD

**Issue by warvstar** [wasm3/wasm3#114]
I've been trying to get access to native memory, but it doesn't appear possible to read or write using either the return value or by passing a ptr.

If such a feature is not available, where should I start looking into to get something like this working? I've tried passing as ssize_t and casting to pointer as well, but nothing. Same for x86 or x64 build.

Edit: fixed a typo

native side
```
ssize_t get_data(ssize_t* data2) {
    *data2 = data;
    return (ssize_t)data;
}
m3_LinkRawFunction(runtime->modules, "env", "get_data", "I(*)", &get_data);
```
wasm side
```
#define WASM_EXPORT __attribute__((used)) __attribute__((visibility ("default")))
extern char* get_data(char*);
WASM_EXPORT void _start() {
	char* data;
	char* data2 = get_data(&data);
	data[0] = 1;
	data2[1] = 1;
}
```

**Comment by vshymanskyy** [comment]
You're using raw functions incorrectly.

**Comment by vshymanskyy** [comment]
It's not a very good idea to provide access to native memory for a Wasm module, as it essentially can break the sandbox (do whatever it wants with the system).

In this case, the Raw function is not correctly defined on the native side. Check out this:
https://github.com/wasm3/wasm3/blob/c45fecf107fcf6f1665647b33fc9bc9d7a710d95/source/m3_api_libc.c#L47

**Comment by warvstar** [comment]
That makes sense. Now that I think about it, it would make more sense to
allocate the memory in a module and have the native side grab a ptr to it.

**Comment by vshymanskyy** [comment]
Exactly :)

**Comment by warvstar** [comment]
So as this is not an actual issue, I'll close this.
Thanks for the help!
