### ISSUE TITLE
build shared library

### ISSUE THREAD

**Issue by prabirshrestha** [wasm3/wasm3#116]
Would it be possible to have `libm3.so` and `libm3.dll`?

**Comment by vshymanskyy** [comment]
It's not supported out of the box, however you can build one.
I'm wondering why do you need this, as shared libraries are meant to be shared between multiple applications. This also introduces versioning problems, etc.
Wasm3 is a tiny library (~120Kb) so static linking should not be an issue.

**Comment by prabirshrestha** [comment]
This is more for languages like c# where static compilation is impossible.

Currently it is a low priority for me. My though was to have the same wasm3 runtime in multiple languages.

**Comment by vshymanskyy** [comment]
This might be interesting in future, however currently Wasm3 API is not stable, so I see no point in providing and supporting a dynamic library version
