### ISSUE TITLE
Rudimentary perf comparison: x86_64 v.s. arm64

### ISSUE THREAD

**Issue by taskx6004** [wasm3/wasm3#117]
### Environment:

x86_64: MacOS, Stock Clang/LLVM, 2.3 GHz Quad-Core Intel Core i5 
Compiler:   AppleClang
Build Type: Release
LTO:        ON

arm64: Nvidia Jetson TX2: JetPack4.3 
Compiler:   GNU
Build Type: Release
LTO:        ON

## x86_64
./run-wasi-test.py 
=== Simple WASI test ===
../build/wasm3 ./wasi/test.wasm cat ./wasi/0.txt
Result: <Empty Stack>

=== Simple WASI test (wasm-opt -O3) ===
../build/wasm3 ./wasi/test-opt.wasm cat ./wasi/0.txt
Result: <Empty Stack>

=== mandelbrot ===
../build/wasm3 ./benchmark/mandelbrot/mandel.wasm 128 4e5
100.00%
Elapsed time: 592.93 ms
Result: <Empty Stack>

=== mandelbrot (doubledouble) ===
../build/wasm3 ./benchmark/mandelbrot/mandel_dd.wasm 128 4e5
100.00%
Elapsed time: 3233.25 ms
Result: <Empty Stack>

=== C-Ray ===
cat ./benchmark/c-ray/scene | ../build/wasm3 ./benchmark/c-ray/c-ray.wasm -s 128x128
Rendering took: 0 seconds (86 milliseconds)
Result: <Empty Stack>

=== smallpt (explicit light sampling) ===
../build/wasm3 ./benchmark/smallpt/smallpt-ex.wasm 16 64
Rendering (16 spp) 100.00%
Elapsed: 1412.0 ms
Result: <Empty Stack>

=== STREAM ===
../build/wasm3 ./benchmark/stream/stream.wasm
Result: <Empty Stack>

=== Self-hosting ===
../build/wasm3 ./self-hosting/wasm3-fib.wasm
Result: <Empty Stack>

=== Brotli ===
cat ./benchmark/brotli/alice29.txt | ../build/wasm3 ./benchmark/brotli/brotli.wasm -c
Result: <Empty Stack>

=== CoreMark ===
../build/wasm3 ./benchmark/coremark/coremark-wasi.wasm
Result: <Empty Stack>

{'crashed': 0, 'failed': 0, 'timeout': 0, 'total_run': 10}

## arm64
./run-wasi-test.py 
=== Simple WASI test ===
../build/wasm3 ./wasi/test.wasm cat ./wasi/0.txt
Result: <Empty Stack>

=== Simple WASI test (wasm-opt -O3) ===
../build/wasm3 ./wasi/test-opt.wasm cat ./wasi/0.txt
Result: <Empty Stack>

=== mandelbrot ===
../build/wasm3 ./benchmark/mandelbrot/mandel.wasm 128 4e5
100.00%
Elapsed time: 4120.20 ms
Result: <Empty Stack>

=== mandelbrot (doubledouble) ===
../build/wasm3 ./benchmark/mandelbrot/mandel_dd.wasm 128 4e5
100.00%
Elapsed time: 30594.11 ms
Result: <Empty Stack>

=== C-Ray ===
cat ./benchmark/c-ray/scene | ../build/wasm3 ./benchmark/c-ray/c-ray.wasm -s 128x128
Rendering took: 0 seconds (562 milliseconds)
Result: <Empty Stack>

=== smallpt (explicit light sampling) ===
../build/wasm3 ./benchmark/smallpt/smallpt-ex.wasm 16 64
Rendering (16 spp) 100.00%
Elapsed: 9026.3 ms
Result: <Empty Stack>

=== STREAM ===
../build/wasm3 ./benchmark/stream/stream.wasm
Result: <Empty Stack>

=== Self-hosting ===
../build/wasm3 ./self-hosting/wasm3-fib.wasm
Result: <Empty Stack>

=== Brotli ===
cat ./benchmark/brotli/alice29.txt | ../build/wasm3 ./benchmark/brotli/brotli.wasm -c
Result: <Empty Stack>

=== CoreMark ===
../build/wasm3 ./benchmark/coremark/coremark-wasi.wasm
Result: <Empty Stack>

{'crashed': 0, 'failed': 0, 'timeout': 0, 'total_run': 10}

Is there anything could be improved by adjusting compiler parameters? or the arch determined it's not a good platform to do this tail-chaining style interpretation on this arm64 implementation.

Thanks.

**Comment by MaxGraey** [comment]
Could you share compiler's flags? And did you try use clang for arm64?

**Comment by taskx6004** [comment]
I am working on llvm compiling at the moment, I used the default build script. Thanks for responding, i will update in a day or two.

**Comment by vshymanskyy** [comment]
Why do you think there's a problem with TCO? For ARM64 it shoild work like a charm.
However your specific CPU may be not very good at running this type of code (due to cache architecture, etc).

**Comment by vshymanskyy** [comment]
Also, the CoreMark test does not report it's result here. You should run it separately

**Comment by taskx6004** [comment]
Spend some time to build with LLVM-9 on both Linux/X86_64 and Linux/ARM64:
CoreMark had similar scores, (not the previous X86 MacBook, an old laptop with 5gen i5)

arch: arm64 v.s. x86_64
mandelbrot: 3089.61 / 770.24 ms
mandelbrot (doubledouble): 31669.00 / 4609.43 ms
C-Ray: 508 / 105 ms
smallpt: 8406.7 / 1718.6 ms

As @vshymanskyy  indicated, it's most likely the cache size matters
