### ISSUE TITLE
Support --dir flag

### ISSUE THREAD

**Issue by syrusakbary** [wasm3/wasm3#119]
Hi,

All WASI runtimes support the `--dir` flag for preopening a directory.

We are going to release a tool for WAPM that allows other runtimes to be run with the wapm modules.
However this is currently failing on `wasm3` because the lack of support for `--dir` in the `wasm3` executable.

**Comment by syrusakbary** [comment]
More info: https://medium.com/wasmer/introducing-wax-a-webassembly-package-runner-d69943209d58

Note: you can test wasm3 in wax with:

```bash
WAPM_RUNTIME=wasm3 wax cowsay a
```

Note: use this hack if you want to see the arguments provided to the runtime:

```bash
WAPM_RUNTIME=echo wax cowsay a
```

**Comment by vshymanskyy** [comment]
We can add dummy `--dir` handling for now, with full support coming after https://github.com/wasm3/wasm3/issues/79
WDYT?

**Comment by syrusakbary** [comment]
I think that would suffice for now! :)

**Comment by vshymanskyy** [comment]
@syrusakbary 
```sh
WAPM_RUNTIME=./printargs.py
wax cowsay a 
['./printargs.py', '/tmp/wax/_/cowsay@0.2.0/wapm_packages/_/cowsay@0.2.0/target/wasm32-wasi/release/cowsay.wasm', '--dir=.', '--', 'a']
```

So it appears the problem is related to the order of arguments
