### ISSUE TITLE
removing fprintf

### ISSUE THREAD

**Issue by prabirshrestha** [wasm3/wasm3#121]
Finally got wasm3 running inside of vim natively. https://twitter.com/PrabirShrestha/status/1238928939545849856

would it be possible to make optional under a flag? Even better if we can hook up a custom function so can use vim log apis.

```c
 fprintf (stderr, "Result: %" PRIu64 "\n", *(u64*)(stack));  break;
```

Running wasm bytecode shows the following inside of vim.

![image](https://user-images.githubusercontent.com/287744/76690196-05fec200-65fb-11ea-8482-cd61e7c9915a.png)

**Comment by vshymanskyy** [comment]
This will have to be handled along with #41.
Currently, you should be able to remove this by compiling with `d_m3LogOutput` to `0`, i.e. by compiling with `-Dd_m3LogOutput=0` flag
