### ISSUE TITLE
Using the parse_module overload that accepts an istream (in the C++ API wrapper) leads to parse errors

### ISSUE THREAD

**Issue by rstat1** [wasm3/wasm3#124]
The short version here is: 
```c++
wasm3::environment env;
wasm3::runtime rt = env.new_runtime(64 * 1024);`
std::ifstream wasmFile("<insert-path-to-wasm-bin-here>");
wasm3::module mod = env.parse_module(wasmFile);
```
leads to different errors depending on how big your file is. One of the files thats used in your tests caused an "underrun while parsing WASM binary" error, while one of my own files caused an "unknown value_type" error

However if you load a file using C-style IO (ie. with `FILE*`s and fopen, etc.) it works just fine.

Honestly this could just be a simple ID10T error, and if so, my applogies.

**Comment by MaxGraey** [comment]
Did you try this?
```cpp
std::ifstream wasmFile("<insert-path-to-wasm-bin-here>",std::ifstream::binary | std::ifstream::in);
if (wasmFile.is_open()) {
   wasm3::module mod = env.parse_module(wasmFile);
   ...
   wasmFile.close();
}
```

**Comment by rstat1** [comment]
Just tried that, got the same "unknown value_type" error.
