### ISSUE TITLE
Big-Endian systems support

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#125]
I've spent some time adding support for **Big-Endian systems**.
Those can still be found in older macs, networking devices, mainframes, space technology.
Tracking the endeavor here.
- [x] Spec tests pass
- [x] Testing multiple architectures on [GitHub Actions](https://github.com/wasm3/wasm3/runs/581907610) (using **QEMU**)
- [x] `RawFunctions` & `WASI` support

**Comment by vshymanskyy** [comment]
Thanks to QEMU, we can now perform WebAsm and WASI tests for multiple architectures (directly on GH Actions):
- arm, armhf, aarch64
- riscv64
- mips, mips64, mipsel, mips64el
- ppc, ppc64, ppc64le
- s390x
- alpha
- sparc64

**Comment by vshymanskyy** [comment]
Finally! `WASI` support for Big-Endian systems has landed in the master branch :smile:

**Comment by vshymanskyy** [comment]
Keep in mind that on BE systems, the Wasm Linear Memory is still considered Little-Endian.
And the stack is Big-Endian (for performance reasons).
This needs to be taken into account while developing native VM functions, so I've introduced some convenience functions like: `m3ApiReadMem32(ptr)`, `m3ApiWriteMem32(ptr, val)`.
See [m3_api_wasi.c](https://github.com/wasm3/wasm3/blob/master/source/m3_api_wasi.c) for an example.

**Comment by vshymanskyy** [comment]
![image](https://user-images.githubusercontent.com/1506708/79804110-feee7080-836b-11ea-9f0f-a2102ea2af0a.png)

**Comment by turbolent** [comment]
Just wanted to report that wasm3 works well on a PowerPC G4 with Mac OS X 10.5.8, GCC 7.3 👍
