### ISSUE TITLE
Gas Metering (restrict executed instruction count)

### ISSUE THREAD

**Issue by tjpalmer** [wasm3/wasm3#127]
This might be the wrong way to ask a question, but is there some way to control instruction throughput? I'm interested in, for example, "execute no more than n instructions in this next batch" and/or "put a pause of t between each instruction executed". Any chance this already is or could be supported?

I tried reading the source some, and I also read some about the interpreter architecture here, but it's not super clear to me where to look in the code.

**Comment by vshymanskyy** [comment]
I agree it would be a cool feature, along with the execution metering (`gas/fuel`).
However currently it's rather hard to implement. Wasm3 does not provide any way to resume execution after returning to the caller.
This could somehow be achieved using [`asyncify`](https://emscripten.org/docs/porting/asyncify.html)

**Comment by vshymanskyy** [comment]
Oh, this would also allow us to implement multi-threading emulation, i.e. running multiple wasm files on a single native thread.

**Comment by tjpalmer** [comment]
I'm definitely also interested in the multithreading emulation, too. (And meanwhile, I'll see what asyncify can do. Thanks for the tip.)

**Comment by tjpalmer** [comment]
Studying a bit, I think asyncify won't fit my needs, including too big of dependencies. I can't rely on preprocessing for my use case. But with enough effort, I might could reimplement the basic idea in a lighter weight fashion ...

**Comment by vshymanskyy** [comment]
Also please check out this:
https://github.com/wasm3/wasm3/blob/c34e9807b103fcb56bbb0080ecd63a353e9c7a89/source/m3_core.c#L21

It's called one in a while an can be used to return a trap. But as I said, there's no way to resume.

**Comment by vshymanskyy** [comment]
Gas Metering can be performed by instrumenting/pre-processing a wasm file using [`wasm-meter`](https://github.com/ewasm/wasm-metering).

I thought it would be interesting to see the performance impact of this, so I processed CoreMark:
```sh
npm install -g wasm-metering
wasm-meter   coremark-minimal.wasm   coremark-minimal-metered.wasm
```

This requires (a very simple) support from the runtime, so I'll be pushing this implementation upstream.
With this approach, CoreMark shows `~2.1x` slowdown:

![image](https://user-images.githubusercontent.com/1506708/111224732-875eab00-85e7-11eb-8fa4-5e6cd096d16c.png)

Note: the second try fails, as gas was limited to `150000000.0000`

**Comment by vshymanskyy** [comment]
Here's an example of metered CoreMark execution using `pywasm3`:
https://github.com/wasm3/wasm3/blob/fb33ddd3ab8b278a32634b7a0d19c35aa3f02a10/platforms/python/examples/02-metered.py

**Comment by vshymanskyy** [comment]
Gas Metering no longer requires instrumenting the `.wasm` file upfront.
The implementation is now fully independent and self-contained:
https://github.com/wasm3/wasm3/blob/main/docs/Cookbook.md#gas-metering
