### ISSUE TITLE
Strange results for floating point operations

### ISSUE THREAD

**Issue by dov** [wasm3/wasm3#128]
I'm failing to run a simple f32 function, and I wonder if it is just a parsing problem, or if there is something more fundamental that doesn't work.

Consider the following wasm program:

```wast
(module

 (func $add (param $x f32) (result f32)
       local.get $x
       f32.const 1.0
       f32.add)

 (export "add" (func $add)))
```
I now compile to wasm and run it through wasm3:
```
$ wat2wasm addonef32.wat -o addonef32.wasm
$ wasm3 --func add addonef32.wasm 41.0
Result: 1065353216
```

On the other hand the corresponding i32 program works fine:
```wast
(module

 (func $add (param $x i32) (result i32)
       local.get $x
       i32.const 1
       i32.add)

 (export "add" (func $add)))
```
Compiling and running:
```
$ wat2wasm addonei32.wat -o addonei32.wasm
$ wasm3 --func add addonei32.wasm 41
Result: 42
```

wasm3 version was master on git sha1:c34e980

**Comment by vshymanskyy** [comment]
@dov Please check out the `USE_HUMAN_FRIENDLY_ARGS` flag.
https://github.com/wasm3/wasm3/blob/c34e9807b103fcb56bbb0080ecd63a353e9c7a89/source/m3_env.c#L749-L767
Unfortunately we had to disable it by default, as the same app is used for the spec tests.
If this flag is disabled, floating point arguments need to be converted to a binary representation, and results need to be converted back.

Definitely have to fix the default behavior, but this is somewhat related to a bigger issue: #41

**Comment by vshymanskyy** [comment]
@dov hope that helps

**Comment by dov** [comment]
@vshymanskyy Thanks. I just turned on USE_HUMAN_FRIENDLY_ARGS and I then get the expected result. Since all I want is to learn (and run a speed comparison between wasm3 and https://beltoforion.de/article.php?a=muparser :-) ) it's enough for me at the moment.

**Comment by vshymanskyy** [comment]
@dov did you run the speed comparison vs `muparser`. Just curious about the results!

**Comment by dov** [comment]
> @dov did you run the speed comparison vs `muparser`? Just curious about the results!

Sorry, in the end I never did run the speed comparison.
