### ISSUE TITLE
Parsing strangely fails (and potentially leaks memory)

### ISSUE THREAD

**Issue by axic** [wasm3/wasm3#131]
We are using a test case for benchmarking (it is ~18kB, [wasm binary here](https://github.com/ewasm/benchmarking/blob/master/wasm-engines/wasmfiles/guido-fuzzer-find-1.wasm?raw=true)). This test case was generated via fuzzing to find a case where parsing/compilation takes disproportionately long on JITs.

It parses successfully on all the engines we have tried (and it should result in a trap), except on wasm3 it behaves weirdly: parsing seems to succeed, but `m3_FindFunction` can't find the `main` symbol.

Also in this case we seem to be seeing a memory leak of 32 bytes of total.

Sources and logs can be found here at https://github.com/wasmx/fizzy/pull/234:

```
fizzy/execute/guido-fuzzer-find-1/main ERROR OCCURRED: 'Trapped'
 wabt/execute/guido-fuzzer-find-1/main ERROR OCCURRED: 'Trapped'
wasm3/execute/guido-fuzzer-find-1/main ERROR OCCURRED: 'Function "main" not found'
```

```
==1783==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x4a084d in malloc (/home/builder/build/bin/fizzy-bench+0x4a084d)
    #1 0x63857c in m3Malloc (/home/builder/build/bin/fizzy-bench+0x63857c)

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 2 allocation(s).
```

**Comment by vshymanskyy** [comment]
Thanks for reporting.

Please note that although fuzzing infrastructure is prepared for Wasm3, we did not perform much of it. Expect more issues of this kind. We plan to perform fuzzing during stabilization phase, after developing a few more majour features.

**Comment by vshymanskyy** [comment]
@axic there were a lot of fixes after this issue was created. Please re-check with the latest changes, I believe it was fixed already.
Please comment if not, I will re-open the issue.

**Comment by axic** [comment]
You can find the file here: https://github.com/wasmx/fizzy/tree/master/test/benchmarks/stress

I do not have the time to test this currently.

**Comment by axic** [comment]
On dee9389d831a6ed5101155f31d217e47c4ad8175 it seems to be properly terminating with trapped now:
```
fizzy/execute/guido-fuzzer-find-1/main  ERROR OCCURRED: 'Trapped'
fizzyc/execute/guido-fuzzer-find-1/main ERROR OCCURRED: 'Trapped'
 wabt/execute/guido-fuzzer-find-1/main  ERROR OCCURRED: 'Trapped'
```

However during exit it hits an assertion:
```
Assertion failed: (! IsRegisterAllocated (o, i_register)), function AllocateRegister, file /Users/alex/Projects-Hawaii-Changed/fizzy/build/_deps/src/wasm3/source/m3_compile.c, line 323.
Abort trap: 6
```

**Comment by axic** [comment]
On dee9389d831a6ed5101155f31d217e47c4ad8175 it seems to be properly terminating with trapped now:
```
fizzy/execute/guido-fuzzer-find-1/main  ERROR OCCURRED: 'Trapped'
fizzyc/execute/guido-fuzzer-find-1/main ERROR OCCURRED: 'Trapped'
 wabt/execute/guido-fuzzer-find-1/main  ERROR OCCURRED: 'Trapped'
```

However during exit it hits an assertion:
```
Assertion failed: (! IsRegisterAllocated (o, i_register)), function AllocateRegister, file /Users/alex/Projects/fizzy/build/_deps/src/wasm3/source/m3_compile.c, line 323.
Abort trap: 6
```

**Comment by axic** [comment]
With 348031ec9d3fd6ad5c775d186caaf4395dd55975 this back to the previous behaviour:
```
fizzy/execute/stress/guido-fuzzer-find-1/main  ERROR OCCURRED: 'Trapped'
fizzyc/execute/stress/guido-fuzzer-find-1/main ERROR OCCURRED: 'Trapped'
 wabt/execute/stress/guido-fuzzer-find-1/main  ERROR OCCURRED: 'Trapped'
wasm3/execute/stress/guido-fuzzer-find-1/main  ERROR OCCURRED: 'Function "main" not found'
```
