### ISSUE TITLE
Utilize the 'computed goto' technique to dispatch instructions?

### ISSUE THREAD

**Issue by thatname** [wasm3/wasm3#134]
Hi.
After examining the code base, I found that dispatching each instruction takes a indirect function call, Which has more overhead compared to the 'computed goto' technique AFAIK.

**Comment by vshymanskyy** [comment]
Thanks! Our internal tests show that this is much slower. However, `computed goto` may be more memory-efficient on some machines, so it does make sense to have it as an option.
Check out this: https://github.com/wasm3/wasm3/pull/74
Closing this for now. We can continue the discussion as usual.
