### ISSUE TITLE
Esp32-idf-wasi throws "m3_LinkEspWASI: function signature mismatch"

### ISSUE THREAD

**Issue by robinvanemden** [wasm3/wasm3#140]
We encounter an error when running `wasm3`'s `esp32-idf-wasi` example: 

```
Wasm3 v0.4.7 on ESP32, build May 18 2020 12:46:14
Loading WebAssembly...
Fatal: m3_LinkEspWASI: function signature mismatch
Elapsed: 30 ms
```

An early version of the esp32-idf-wasi example runs fine, and the current code looks ok at a first glance  - probably some minor issue?

**Comment by vshymanskyy** [comment]
Thanks for reporting! Is this with the default "hello world" example?

**Comment by robinvanemden** [comment]
Yes - the default "esp32-idf-wasi" example..

**Comment by robinvanemden** [comment]
We were able to resolve this issue by updating the link functions in m3_api_esp_wasi.c with the more recent ones from m3_api_uvwasi.c.

A pull request can be found here:

https://github.com/wasm3/wasm3/pull/142

@vshymanskyy : thanks for keeping the Wasm3 project up and running 😄
