### ISSUE TITLE
Usage as webassembly polyfill via asm.js

### ISSUE THREAD

**Issue by lmcdougald** [wasm3/wasm3#141]
Given that wasm3 can self-host, it seems like wasm3 is one of the best candidates for a WebAssembly polyfill via Emscripten's asm.js target. A quick google search indicated no one has finished a public WebAssembly polyfill. Are there any roadblocks or gotchas with this approach?

**Comment by vshymanskyy** [comment]
This is trivial to achieve, and it actually works.
However it's slow and impractical, as apps can be compiled to asm.js directly.
