### ISSUE TITLE
Native linear memory access on Riscv64

### ISSUE THREAD

**Issue by robinvanemden** [wasm3/wasm3#150]
As an experiment, I am porting one our `ESP32` `WASI` deep neural net demos to a `Riscv64` based Maixduino. Seems to work like a charm: we only needed to set `d_m3Use32BitSlots` to `false` to get the inference itself to work. We are now able to call a WASM exported "pred" function returning the correct integer representing the index of a predicted image category on both `Riscv64` and `ESP32`. Cool! (demo post will follow soon).

Still, in our `ESP32` demo we are also able to access base64 encoded result strings in `Wasm`'s linear memory by doing basic pointer arithmetics. For the ESP32, we currently use `m3_GetMemory()` to obtain a raw pointer to the start of the linear memory and then add the pointer returned by a WASM malloc (cast to long in WASM, and then cast back to a pointer in native code) to locate the start of some input or output char array.

Though this works perfectly on our `ESP32`, we do not seem to be able to get this approach to work in our `Riscv64` example. We played around with different types and ways of casting the returned pointer. But we have not been able to convert the `Wasm` `malloc` returned pointer to the correct native pointer. So any pointers (😅) are more than welcome!

**Comment by vshymanskyy** [comment]
Actually, RISC-V is covered by CI tests: https://github.com/wasm3/wasm3/runs/1615348202?check_suite_focus=true
It passes all WASI tests, which uses Linear Memory extensively. So I'm not sure why enabling `d_m3Use32BitSlots` was even required.
I'll have to try it out on an actual Maixduino, I guess ;)

**Comment by robinvanemden** [comment]
Thanks for your response! It has been a while since I tested Wasm3 on the Maixduino. But I will try again later this week and see if I can figure out what might be have been the issue. I'll keep you posted!

**Comment by vshymanskyy** [comment]
@robinvanemden FYI `wasm3-arduino` library was updated to `v0.4.8`: https://github.com/wasm3/wasm3-arduino/releases/tag/v0.4.8

**Comment by vshymanskyy** [comment]
@robinvanemden Just tried it out. Indeed, MAIXDuino requires `d_m3Use32BitSlots=0`.
Everything else seems to be working fine. Closing for now, but let us know if the issue persists!

**Comment by vshymanskyy** [comment]
Reopened, as we'd like to figure our why `d_m3Use32BitSlots` is not working on RV64.

**Comment by vshymanskyy** [comment]
The issue with 32-bit slots is, that we have several instances of `dereferencing type-punned pointer, that break strict-aliasing rules`.
This will be fixed soon, however it looks like we'll default to 64-bit slots on 64 systems, as it has significant performance impact.
