### ISSUE TITLE
[crash] SIGILL in Compile_BlockStatements

### ISSUE THREAD

**Issue by pventuzelo** [wasm3/wasm3#154]
Hey, 

I triggered a SIGILL during fuzzing inside the function `Compile_BlockStatements`.

https://github.com/wasm3/wasm3/blob/640bf0cc2671f1725234536c3cd4be50de6cc19e/source/m3_compile.c#L2163

Download: [SIGILL_wasm3.zip](https://github.com/wasm3/wasm3/files/4775565/SIGILL_wasm3.zip)

**Comment by pitust** [comment]
This looks like a commpiler assertion, SIGILL is usually triggered by something like the `ud2` instruction.
