### ISSUE TITLE
Clarity about m3_FreeModule

### ISSUE THREAD

**Issue by axic** [wasm3/wasm3#160]
```c
    M3Result            m3_ParseModule              (IM3Environment         i_environment,
                                                     IM3Module *            o_module,
                                                     const uint8_t * const  i_wasmBytes,
                                                     uint32_t               i_numWasmBytes);
    // i_wasmBytes data must be persistent during the lifetime of the module

    void                m3_FreeModule               (IM3Module i_module);
    //  Only unloaded modules need to be freed

    M3Result            m3_LoadModule               (IM3Runtime io_runtime,  IM3Module io_module);
    //  LoadModule transfers ownership of a module to the runtime. Do not free modules once successfully imported into the runtime
```

`FreeModule` says only unloaded modules need to be freed, e.g. before calling `LoadModule`, however it would be nice to be a bit more clear what happens when `LoadModule` fails.

I came to the conclusion no matter `LoadModule` fails or not, once having attempted to call it, `FreeModule` should not be invoked. Is that the correct understanding?

**Comment by vshymanskyy** [comment]
I have created an example of how to reload/restart the wasm file (the Dino game on PyBadge):
https://github.com/wasm3/wasm3-arduino/blob/master/examples/Wasm_PyBadge_Dino/Wasm_PyBadge_Dino.ino

**Comment by axic** [comment]
Thanks, but I think that source is not making it more clear.

> I came to the conclusion no matter LoadModule fails or not, once having attempted to call it, FreeModule should not be invoked. Is that the correct understanding?

Is this correct or wrong? If correct, would it be possible to leave this as a comment in the header?

**Comment by vshymanskyy** [comment]
Should be more clear now. Please let us know if the issue is still relevant

**Comment by axic** [comment]
https://github.com/wasm3/wasm3/blob/main/source/wasm3.h#L219-L222 looks much better now, thanks!

>     // b. m3_LoadModule returned a result.

One final clarification, here do you mean "a successful result"?

**Comment by vshymanskyy** [comment]
That is, returns `m3Err_none` (which is `NULL`),
