### ISSUE TITLE
Arduino examples fatal error

### ISSUE THREAD

**Issue by sigmasoldi3r** [wasm3/wasm3#161]
```
Version 0.4.5
Platform: Arduino
Microcontroller: Arduino Mega 
```
![image](https://user-images.githubusercontent.com/13834659/88278628-fc8d1100-cce2-11ea-922e-3458d1ec7014.png)

When trying to run examples from Arduino library it won't work:

The examples_pio/Wasm_Advanced/wasm_vm:
```
10:57:21.307 -> 
10:57:21.307 -> Wasm3 v0.4.5, build Jul 23 2020 10:56:29
10:57:21.307 -> Fatal: NewRuntime failed
```
Also this example needs some tuning: `#define LED_PIN             13` line is commented out and won't compile if not uncommented.

The blink example:
```
12:45:39.569 -> 
12:45:39.569 -> Wasm3 v0.4.5, build Jul 23 2020 12:45:02
12:45:39.569 -> Fatal: FindFunction memory allocation failed when acquiring a new M3 code page
```

**Comment by vshymanskyy** [comment]
Arduino Mega is not among supported boards.
