### ISSUE TITLE
Any special techniques that Wasm3 used for getting better performance?

### ISSUE THREAD

**Issue by Becavalier** [wasm3/wasm3#163]
As I know, the following techniques are currently being used in Wasm3:

1. Threaded code;
2. Register-based computing model;

And, any other stuff?

BTW, how can you do a convenient type-checking (like, for unreachable code) within a register-based machine? I think this can be easily done on a stack-machine as Wasm designed.

**Comment by vshymanskyy** [comment]
Basically, those two. Also, it appears that this particular (Tail Calls-based) threaded code works really well on modern architectures.
Type-checking is performed on WASM level directly, and at actual threaded code execution time.

Hope those answers help.
