### ISSUE TITLE
Building wasm3 for arm-none-eabi

### ISSUE THREAD

**Issue by valexandru** [wasm3/wasm3#166]
Hi! 

I saw in the main README file that arm architecture is supported and I am trying to build libm3 for arm-none-eabi. Is there any documentation on how to do this?

**Comment by jiayihu** [comment]
Hi, i'm having the same issue. Did you manage to do it?

**Comment by johandroid** [comment]
Hi @valexandru , did you success on building for arm? How did you do it?

**Comment by valexandru** [comment]
Hello, some time has passed since then. But if I remember correctly, I gave up on trying to use this one and found [another interpretor](https://github.com/qmonnet/rbpf.git) that was suitable for my case. Hope it helps! :D
