### ISSUE TITLE
Plans for SIMD

### ISSUE THREAD

**Issue by jiayihu** [wasm3/wasm3#169]
Is there any estimate on the support of SIMD instructions?

**Comment by ogoudron** [comment]
Maybe this could help
https://github.com/simd-everywhere/simde

**Comment by vshymanskyy** [comment]
@ogoudron Yes I already considered using SIMDe, but it currently supports emulating other ISAs on WASM, not the other way around.
See https://github.com/simd-everywhere/simde/issues/76
But it might be implemented in future...

**Comment by nemequ** [comment]
I just added an implementation of WASM SIMD to SIMDe.  It still needs work (see [the commit message](https://github.com/simd-everywhere/simde/commit/db758eb4c473f810689d298e1765d419af44a676)), but it's functional.
