### ISSUE TITLE
Error: function lookup failed ('_start')

### ISSUE THREAD

**Issue by nu8** [wasm3/wasm3#170]
If I have a Go file like this:

~~~go
package main
import "fmt"

func main() {
   fmt.Println("May")
}
~~~

I can compile like this:

~~~ps1
$env:GOARCH = 'wasm'
$env:GOOS = 'js'
go build -o main.wasm a.go
~~~

but then I get this error:

~~~
PS C:\Users\spenny\Desktop> .\wasm3-win-x64.exe .\main.wasm
Error: [Fatal] repl_call: function lookup failed
Error: function lookup failed ('_start')
~~~

**Comment by vshymanskyy** [comment]
Only `TinyGo` is supported out of the box. `Go` compiler seems to have different assumptions about the runtime.

**Comment by vshymanskyy** [comment]
Looks like we'll have to wait for this to happen: https://github.com/golang/go/issues/31105
