### ISSUE TITLE
CNCF-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [wasm3/wasm3#171]
Hello Wasm3 team,

I'm one of the co-chairs of the CNCF SIG-Runtime. I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. For example, a general overview of the project and its use cases.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by vshymanskyy** [comment]
Thanks, we'll check it out!

**Comment by raravena80** [comment]
Hi @vshymanskyy, 

Checking in, would the team be interested in presenting in our next CNCF SIG-Runtime meeting?

Thanks!
