### ISSUE TITLE
How to share M3Runtime, M3Environment with dynamic loaded/unloaded M3Modules

### ISSUE THREAD

**Issue by vulptex** [wasm3/wasm3#172]
Hi,

i have a question regarding reusing the runtime and environment:

1. create a global M3Runtime/M3Environment
2. than execute a module by: m3_ParseModule, m3_LoadModule, m3_FindFunction, m3_CallWithArgs
3. m3_FreeModule
4. goto: 2-3 -> memory leaks
6. SegFault when the global  m3_FreeRuntime kicks in (which i expect, we now have a lot of dangling modules :-))

leak:

```shell
==27100==    by 0x4D75960: m3_Malloc (m3_core.c:109)
==27100==    by 0x4D5CE45: NewCodePage (m3_code.c:19)
==27100==    by 0x4D59AF5: AcquireCodePageWithCapacity (m3_env.c:896)
==27100==    by 0x4D59B58: AcquireCodePage (m3_env.c:913)
==27100==    by 0x4D711D3: AcquireCompilationCodePage (m3_compile.c:58)
==27100==    by 0x4D75642: Compile_Function (m3_compile.c:2088)
==27100==    by 0x4D597B2: m3_FindFunction (m3_env.c:715)
==27100==    by 0x4D46F58: cactus::WasmInterpreterApp::calc() (wasm_interpreter_app.cpp:92)
```

crash:

```shell
==27100==    by 0x4D759A5: m3_Free (m3_core.c:123)
==27100==    by 0x4D5B4B5: m3_FreeModule (m3_module.c:40)
```

The crash is obvious as the design seems not support  freeing modules within the lifetime of M3Runtime.

I have the following ideas, to be honest i haven't looked into wasm3 in depth for now (started today tinkering with it):

- remove the module from the modules list after freeing
- reuse an already loaded module instead of creating a new one within m3_ParseModule

**Comment by vshymanskyy** [comment]
I have created an example of how to reload/restart the wasm file (the Dino game on PyBadge):
https://github.com/wasm3/wasm3-arduino/blob/master/examples/Wasm_PyBadge_Dino/Wasm_PyBadge_Dino.ino

**Comment by vulptex** [comment]
@vshymanskyy thx.
