### ISSUE TITLE
Docs or examples of providing a standard host interface other than WASI

### ISSUE THREAD

**Issue by novocodev** [wasm3/wasm3#173]
I need to provide and alternative (to WASI) standard host interface to all WASM binaries that run in my runtime.

Trying to figure out the level of difficulty implementing this in wasm3

Are there any docs or examples of adding a custom host interface?

Or can anyone provide a bullet list of tasks required to achieve this?

**Comment by vshymanskyy** [comment]
Check out this example: https://github.com/wasm3/wasm3-arduino/tree/master/examples_pio/Wasm_Advanced
Hope it helps. If not, feel free to continue the discussion here!
