### ISSUE TITLE
Reference types

### ISSUE THREAD

**Issue by turbolent** [wasm3/wasm3#177]
Are there any plans to add support for [reference types](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md).

What would be needed to be changed to support it?

**Comment by vshymanskyy** [comment]
Reference types includes a lot of different things. Which part of it are you most interested in?

**Comment by turbolent** [comment]
I'm mostly interested in allowing host references to be represented directly by type `externref` (see https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md).

**Comment by turbolent** [comment]
@vshymanskyy would you be able to point me to where and describe on a high-level how a new value type can be added?

**Comment by chances** [comment]
@vshymanskyy Why was this issue closed?

**Comment by vshymanskyy** [comment]
it's in the backlog
