### ISSUE TITLE
benchmarks requirement: CoreMark.wasm with minimum dependencies on the API

### ISSUE THREAD

**Issue by atenjin** [wasm3/wasm3#181]
The reason we have this issue is from this discuss in Discard: [link](https://discord.com/channels/671415645073702925/671423158414213181/781271560526364723)

At first we what to do some benchmarks between [wasmi](https://github.com/paritytech/wasmi) and wasm3 by ourself.
However we notice that wasmi do not support WASI for the purpose for wasmi is used in blockchain, which the situation does not need to support low level system call. And other situation like pure calculation also do not need WASI. So some interpreter do not support WASI. 

Currently, wasm3 does not have a `CoreMark.wasm` benchmark case to test the pure part for an interpreter. So we hope you guys could provide some suitable wasm cases like `CoreMark.wasm` or something else to support to run benchmarks again.

And in our way, we could do the benchmarks for wasmi by ourself, and compare with wasm3, and submmit result to wasm3 repo. :p

**Comment by vshymanskyy** [comment]
Also, I'm thinking about moving CoreMark to a separate repo.

**Comment by vshymanskyy** [comment]
CoreMark builds have been moved to a separate repo: https://github.com/wasm3/wasm3-coremark
It also includes a `minimal` build of CoreMark.
@atenjin please check out `python` and `js` examples.

**Comment by atenjin** [comment]
Thanks! We will check later.

**Comment by vshymanskyy** [comment]
@atenjin FYI: 
> VM Matters: A Comparison of WASM VMs and EVMs in the Performance of Blockchain Smart Contracts
https://arxiv.org/abs/2012.01032

**Comment by atenjin** [comment]
@vshymanskyy 
Thanks for you information! This is very useful for us.

**Comment by vshymanskyy** [comment]
@atenjin check out this as well:
https://github.com/wasm3/wasm3/issues/127#issuecomment-799774730
