### ISSUE TITLE
Setting #define d_m3MaxFunctionStackHeight 128 cause Arduino to c

### ISSUE THREAD

**Issue by kthakore** [wasm3/wasm3#187]
Using the following code in rust I make a wasm with: 

`cargo build --target wasm32-unknown-unknown --release`
I also optimize the wasm and strip it
```
wasm-opt -O3 target/wasm32-unknown-unknown/release/app.wasm -o app.wasm
wasm-strip app.wasm
xxd -iC app.wasm  > app.h
```

```
#![no_std]

#[macro_use]
extern crate alloc;
use alloc::fmt;

#[no_mangle]
pub extern "C" fn _call() -> u32 {
    
    unsafe {
            debug(fmt::format(format_args!("CAPABILITY_TYPE {}", capability_type)));
            debug(fmt::format(format_args!("input_type {}", input_type)));
     }

  return 0;
}
```
However when I call it in wasm3  on nanoble33 (latest wasm3) 

``` 
   M3Result result = m3Err_none;
    result = m3_FindFunction (&_call, runtime, "_call");
    if (result) FATAL("FindFunction", result);
      const char* x_argv[1] = { NULL };
      result = m3_CallWithArgs(_call, 0, x_argv);

    long ptr = *(uint64_t*)(runtime->stack);
    Serial.print("_call: ");
    Serial.println(ptr);
```
I get the following error
```Error: compiling function overrun its stack height limit ()```

If I try to change the stack height limit from 64
```
#define d_m3MaxFunctionStackHeight 128

#include <wasm3.h>
```

It crashes the Arduino device.

**Comment by vshymanskyy** [comment]
Can't build your rust code. Please attach the whole project + the wasm binary.

**Comment by kthakore** [comment]
@vshymanskyy Thanks so much! 
 see https://github.com/kthakore/wasm3-function-stack-height-bug
`app.wasm` is the binary and I have the generated header file in the arduino project (wasm3_arduino)

**Comment by kthakore** [comment]
If I change this line 
https://github.com/kthakore/wasm3-function-stack-height-bug/blob/master/wasm3_arduino/wasm3_arduino.ino#L2
to `#define d_m3MaxFunctionStackHeight 128` it will crash on device

**Comment by vshymanskyy** [comment]
First of all, you cannot just change the `#define d_m3MaxFunctionStackHeight` in your source file, and expect it to work.
You need to define it in your build system, or change directly in `m3_config.h`. This applies to other configs as well.

**Comment by vshymanskyy** [comment]
Running on the latest `master`, I do not see the issue, however it definitely was there in `0.4.7`.

**Comment by vshymanskyy** [comment]
@kthakore also in your ` m3ApiRawFunction(m3_debug)`, you forgot to call `m3ApiSuccess();` at the end, which leads to some undefined behavior.

**Comment by vshymanskyy** [comment]
`wasm3-arduino` library was updated to `v0.4.8`: https://github.com/wasm3/wasm3-arduino/releases/tag/v0.4.8
Should be fixed now.

**Comment by kthakore** [comment]
Awesome thank you!!
