### ISSUE TITLE
How do I load a local WASM file？

### ISSUE THREAD

**Issue by cl-sky** [wasm3/wasm3#188]
I want to load the local WASM file on the iOS platform, I want to know what I should do

**Comment by vshymanskyy** [comment]
Sorry, this is not related to wasm3. You need tomliad wasm binary to a memory buffer (using any API you have), and pass that to Wasm3.

**Comment by atdrendel** [comment]
@cl-sky I've been writing a blog series about this topic using Wasm3. You can find it [here](https://shareup.app/blog/using-webassembly-on-ios/), if you're interested. I think it will get you pretty far.
