### ISSUE TITLE
MSVC reports syntax error in source/extra/wasi_core.h after "Whence fixes" commit (05e1865)

### ISSUE THREAD

**Issue by emiltayl** [wasm3/wasm3#189]
After the latest commit (05e1865) I am no longer able to compile wasm3 using MSVC. 

Compiling results in many (>100) errors like this:

```
wasm3\source\extra/wasi_core.h(38): error C2143: syntax error: missing ')' before 'alignof'
wasm3\source\extra/wasi_core.h(38): error C2143: syntax error: missing '{' before 'alignof'
```

I suspect the issue is caused by the following lines having been removed from wasi_core.h:

```
# if defined (M3_COMPILER_MSVC)
#  define _Static_assert(...)
#  define __attribute__(...)
# endif
```

**Comment by vshymanskyy** [comment]
@emiltayl The build failure is fixed.
We have now `no-uvwasi` CI tests for Linux, Mac, Windows. One of the test fails, but at least it's the same on all platforms.
I hope to fix this later this week.

**Comment by vshymanskyy** [comment]
@sinkingsugar maybe you can take a look at this test failure..
`../build-simple-wasi/wasm3 ./wasi/test.wasm cat /wasi/0.txt`, says `Cannot open /wasi/0.txt`
SimpleWASI was not covered by adequate tests previously, so we missed this issue.

**Comment by sinkingsugar** [comment]
@vshymanskyy I've fixed it locally on my fork, I will try to make a PR. I think it worked on windows only, every unix platform failed. Something to do with preloads.
My fork has diverged a lot but I will try to cook up a PR!

**Comment by vshymanskyy** [comment]
Yes, the issue seems to be resolved. Thanks!
