### ISSUE TITLE
Obtaining stack trace after trap is encountered

### ISSUE THREAD

**Issue by t-veor** [wasm3/wasm3#190]
Hello,

I would like a way to obtain a stack trace through the API whenever a trap is encountered. I have found the `d_m3LogStackTrace` macro, which when a trap is triggered prints the function name and the stack pointer of every function in the stack as it unwinds, but this just prints them to stdout with `printf`. Ideally I'd like to know the code offset of the actual function triggering the trap, as well as the offsets of the callsites of every single function consequently on the stack. It doesn't seem like this is possible with the way wasm3 currently works?

Looking at how traps are propagated, I think a (fairly) noninvasive way of doing this is changing the definition of `m3_ret_t` to something like:
```c
typedef struct
{
    pc_t pc;
    mstack_t sp;
    cstr_t functionName;
} BacktraceRecord;

typedef struct
{
    void * trapType;
    BackTraceRecord * backTrace;
    size_t backTraceLen;  // Could be an array or some linked list, doesn't really matter
    size_t backTraceCapacity;
} TrapInfo;

typedef TrapInfo * m3_ret_t;
```

And at trap sites, you would do e.g.:
```c
d_m3Op  (Unreachable)
{
    return CREATE_TRAP(trapUnreachable); // Creates a trap and populates a backtrace record with the current function context
}
```

And in the implementations of `Call` and `CallIndirect`,
```c
d_m3OpDef  (Call)
{
    // ...

    m3ret_t r = Call (callPC, sp, _mem, d_m3OpDefaultArgs);

    if (r == 0)
    {
        // ...
    }
    else
    {
        PUSH_STACK_CONTEXT(r); // pushes the current function context onto the trap info record
        return r;
    }
}
```

or something similar. The idea being that eventually the `TrapInfo` gets propagated all the way back up to whatever `m3_Call` or `m3_CallWithArgs` that invoked it and the caller can inspect the value to find if a trap happened and the stack trace if so.

Unfortunately of course this changes the public API, but I'm not sure how else something like this could be achieved. What are other's thoughts on a proposal like this?

**Comment by vshymanskyy** [comment]
Really interesting. I think this can be added quite easily.
We can allocate stack trace memory dynamically, when trap occurs.
Output of the stack trace can be done on the app level then.

**Comment by vshymanskyy** [comment]
`offsets of the callsites of every single function consequently on the stack` -> this is currently not possible.
However we could add some kind of `wasm binary offset <-> vm code` mapping.
This would allow us to support symbolic debugging in future: https://github.com/wasm3/wasm-debug

**Comment by vshymanskyy** [comment]
Merged
