### ISSUE TITLE
Build of EMSCRIPTEN target fails

### ISSUE THREAD

**Issue by BlueSolei** [wasm3/wasm3#193]
I am trying to build wasm3 to wasm target using Emscripten, as described [here](https://github.com/wasm3/wasm3/tree/master/platforms/emscripten).
I am building it on `Ubuntu 20.04` with `Emscripten 2.0.12`

I started with:
```console
source /opt/emsdk/emsdk_env.sh --build=Release
mkdir -p build
cd build
cmake -GNinja -DEMSCRIPTEN=1  ..
ninja
```

first failure:
```
CMake Error at build/_deps/libuv-src/CMakeLists.txt:305 (add_library):
  The install of the uv target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
```
Fix: `cmake -GNinja -DEMSCRIPTEN=1 -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON ..`

Now the build starts, but fails with these error messages:
```
deps/libuv-src/src/unix/linux-inotify.c:71:13: fatal error: no member named 'inotify_fd' in 'struct uv_loop_s'
  if (loop->inotify_fd != -1)
      ~~~~  ^
=_deps/libuv-src/src/unix/linux-syscalls.c:154:10: fatal error: implicit declaration of function 'syscall' [-Wimplicit-function-declaration]
  return syscall(__NR_sendmmsg, fd, mmsg, vlen, flags);
         ^
```

The `implicit declaration of function 'syscall'` is easy to solve, the second one I am still failing to understand.
But since this is a supported platform, shouldn't it be built right out of the box?
Any help would be appreciated.

**Comment by vshymanskyy** [comment]
Probably just need to disable WASI support, or switch to a simpler implementation.
Try adding `-DBUILD_WASI=simple` or `-DBUILD_WASI=none` to cmake flags

**Comment by BlueSolei** [comment]
This works, thanks.
Shouldn't the complete project be buildable as a wasm module? include WASI support?

**Comment by vshymanskyy** [comment]
`-DBUILD_WASI=simple` includes a simple WASI implementation, but I'm not sure if (and to which extent) Emscripten can handle this. Let me know if it works ;)
