### ISSUE TITLE
Support multiple functions in same module sharing an implementation

### ISSUE THREAD

**Issue by atdrendel** [wasm3/wasm3#198]
Currently, if multiple named exported functions share a single implementation, Wasm3 only exposes one of the exported functions to clients. This is because only the first name is saved to `M3Function` inside `ParseSection_Export()`

```c
if (not io_module->functions [index].name)
{
  io_module->functions [index].name = utf8;
  utf8 = NULL; // ownership transfered to M3Function
}
```

A simple WebAssembly module illustrates this problem:

```wasm
(module
  (type (;0;) (func (result i32)))
  (func (;0;) (type 0) (result i32)
    i32.const 42)
  (export "first" (func 0))
  (export "second" (func 0)))
``` 

If you try to use `m3_FindFunction()` to find `first()`, you will succeed. However, trying to find `second()` will fail.

We have run into this problem when using Wasm3 with Libsodium. Libsodium exposes a number of different functions that wrap private constants, some of which are equal. These functions are all compiled down into the same WebAssembly function implementation with different exported names.

**Comment by atdrendel** [comment]
I've opened [this pull request](https://github.com/wasm3/wasm3/pull/199) with a possible fix.

**Comment by vshymanskyy** [comment]
merged
