### ISSUE TITLE
Implement type checking for call_indirect

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#2]
https://github.com/vshymanskyy/wasm3/blob/f189e42c3e0eef77b6610b671ae642c566b8fe69/source/m3_exec.c#L46

To reproduce this problem, run the spec test:
```sh
./run-spec-test.py ./core/call_indirect.json
```
**Actual result:** It fails with a few items like this:
![image](https://user-images.githubusercontent.com/1506708/68856885-40f2f680-06ea-11ea-952a-f210a91a1c29.png)

**Expected result:** spec test is passed

**Comment by ThePrimeagen** [comment]
I may play around with this.  Just doing some exploration.
