### ISSUE TITLE
Start function is not called during instantiation

### ISSUE THREAD

**Issue by axic** [wasm3/wasm3#202]
It seems during some recent (in the last 6 months) changes, the invoking of `InitStartFunc` has moved from [`m3_LoadModule`](https://github.com/wasm3/wasm3/blob/v0.4.7/source/m3_env.c#L665) (i.e. as part of instantiation) to [`m3_FindFunction`](https://github.com/wasm3/wasm3/blob/master/source/m3_env.c#L752) (i.e. as part of the first successful function lookup after instantiation).

As far as I know the [wasm specification mandates](https://webassembly.github.io/spec/core/syntax/modules.html#syntax-start) the start function to be invoked during instantiation.

Is there a good reason for this change?

Update: I see [this as the reasoning](https://github.com/wasm3/wasm3/blob/master/source/m3_env.c#L696-L697):
>        // Start func might use imported functions, which are not liked here yet,
>        // so it will be called before a function call is attempted (in m3_FindFuSnction)

As a workaround would it be possible to have something like `m3_FindFunction(&func, runtime, "")` also work as a trigger or have a separate export like `m3_ExecuteStart(runtime)`?

**Comment by vshymanskyy** [comment]
The specification mandates that it is automatically called (which is still true, even if it happens in `FindFunction`).
We can add something like `m3_InitModule(module)`, as runtime can have multiple modules loaded.

Also, can you please explain why this is causing issues for you?

**Comment by gumb0** [comment]
It is certainly part of the instantiation according to the spec, see step 15 in https://webassembly.github.io/spec/core/exec/modules.html#instantiation

**Comment by vshymanskyy** [comment]
So again, what's the motivation about this request? @gumb0

**Comment by axic** [comment]
> So again, what's the motivation about this request?

Many abstraction layers where multiple engines are used ([one example is in fizzy](https://github.com/wasmx/fizzy/blob/master/test/utils/wasm_engine.hpp)) are inspired by the wasm specification and have distinct steps: 1) instantiation; 2) finding a function and executing it.

With the current wasm3 API it is not possible to complete instantiation as per the specification, unless that abstraction layer is broken and an exported function is called in the "instantiation phase". This also means it is not possible to benchmark/compare instantiation across different engines.

Some engines execute the start function as part of instantiation, while others have a specific function for it to be called by the embedder. An example is wabt, which used to have a `RunStartFunction` function, but for a while they have also moved that to be part of instantiation. I do not currently know of any engine (apart from wasm3) which does not execute start as part of instantiation.

I understand if you do not want to do it as part of `LoadModule`, but having a way to execute the start function without triggering an export would be appreciated.

**Comment by vshymanskyy** [comment]
Please try calling `m3_RunStart(module)`.
This is an additional (and optional) API. It won't attempt to run the start function on the same module twice.

**Comment by axic** [comment]
Thank you, that sounds great, will give it a try today!

**Comment by vshymanskyy** [comment]
Basically, we already had the function, it wasn't exposed as an API ;)

**Comment by axic** [comment]
Works well, thanks.

> Basically, we already had the function, it wasn't exposed as an API ;)

Yep, did not wanted to use internals. Albeit it seems they were exported already, just the prototype missing in the public header.
