### ISSUE TITLE
Question about memory shrinking

### ISSUE THREAD

**Issue by AGreat1** [wasm3/wasm3#206]
Hi all!

I'm wondering whether there is any way I can ask the runtime to shrink its memory footprint? Let's say I use wasm3 for a plugin framework, and due to some things happening in the host system, some plugins do some hard work, and need to grow their memory with a few pages. Once this is over, I would like to leave more room for other things happening in the system. Does wasm3 have an API, or some internal smarts to shrink the memory consumption e.g. when the complete stack is unwound? Is there any alternative to having to persist the plugin state and then restart it?

**Comment by vshymanskyy** [comment]
@AGreat1 The WASM spec only allows growing the memory:
https://webassembly.github.io/spec/core/exec/modules.html#grow-mem
BUT.
Nothing restrains us from having an `imported function` that shrinks the memory.
Say, call `wasm3.mem_shrink(n)` from your wasm module, while on Wasm3 native code side:
```cpp
#include <m3_env.h>

m3ApiRawFunction(wasm3_mem_shrink)
{
    m3ApiReturnType (uint32_t)
    m3ApiGetArg     (uint32_t, pages_to_shrink)

    IM3Memory memory = & runtime->memory;

    M3Result r = ResizeMemory (runtime, memory->numPages - pages_to_shrink);

    // return new mem size in pages
    m3ApiReturn(memory->numPages);
}

...
m3_LinkRawFunction (module, "wasm3", "mem_shrink",            "i(i)",   &wasm3_mem_shrink)
```

This was not tested, but should work.
But keep in mind, that the wasm module runtime (i.e. any heap allocators that reside inside) need to take into account the new memory constraints.

**Comment by AGreat1** [comment]
Thanks for the swift answer! The solution would work well for me. I'll reopen this issue if I encounter problems, but for now I'll close it with gratitude. :)
