### ISSUE TITLE
Updates to wasm3 to pass security review

### ISSUE THREAD

**Issue by waywardgeek** [wasm3/wasm3#207]
Our team at Google is trying to use wasm3 for a project we hope to open-source, but wasm3 must pass a security review before we can launch any Google project using it.  Would you be receptive to pull requests motivated by the security review?  This might include occasional actual security patches, but most suggested changes are designed to simplify the security review process, e.g. making it possible to sign off on the security of a function in a file without having to read lots of code in other files.

Our team trying to use wasm3 as an extra sandboxing layer that hopefully will enable us to run fully untrusted code on our servers in security-sensitive applications, where security is more important than speed.  We're using the minimum possible built-in APIs, not wasi.  I'm pulling your latest version into our internal repo right now, and I see there appears to be encouraging improvements in the security side of wasm3, e.g. the new m3ApiCheckMem calls.  Is our sandboxing application for wams3 an intended use case of wasm3?

IThanks,
Bill

**Comment by vshymanskyy** [comment]
Hey Bill. Sandboxing/SFI is definitely one of the intended use-cases of wasm3.
PRs are welcome, as usual! Most changes are accepted, as soon as they are not degrading the performance (or increase memory usage) too much. Public API is also not stable yet, so we can change it at any time.

Wasm3 didn't yet undergo any serious fuzz testing, so definitely there's room for improvement in terms of security.

**Comment by waywardgeek** [comment]
Awesome!  We definitely will enhance fuzzing.  That is already a request from the security reviewer.
