### ISSUE TITLE
`m3ApiCheckMem`: Nullpointer dereference and memory accessed from the stack always out of bounds

### ISSUE THREAD

**Issue by Naios** [wasm3/wasm3#210]
0b69623b3

```cpp
# define m3ApiCheckMem(off, len)   { if (UNLIKELY(off == _mem || ((u64)(off) + (len)) > ((u64)(_mem)+runtime->memory.mallocated->length))) m3ApiTrap(m3Err_trapOutOfBoundsMemoryAccess); }
```

---

The recently introduced macro `m3ApiCheckMem` has following issues:

When the interpreted wasm code hasn't made any allocations yet, the field `runtime->memory.mallocated` field is `nullptr` and thus will always result in a `nullptr` dereference if a memory region is checked.

This can happen if we only pass values that reside itself on the stack to a bound function.
Additionally it seems like that the `m3ApiCheckMem` macro always rejects addresses that point to the wasm stack, and only the wasm heap is considered as valid offset, whereas it should be legal to also reference values from the wasm stack.

**Comment by vshymanskyy** [comment]
@Naios there are no such things, as `reference values from the wasm stack`.
You cannot get a pointer to wasm stack value in wasm.
You may need a `shadow stack` in the linear memory, to overcome this limitation.

`m3ApiCheckMem` will fail if NULL (from linear memory) is referenced - this is intended.

If linear memory is not allocated, I think it's invalid  to call native functions that accept linear memory offset. Will re-check this case.

**Comment by Naios** [comment]
@vshymanskyy Thank you for your fast response. You are right and offsets pointing into linear memory should be fine, I should have invested more time into analysis, before opening this ticket.

Unfortunatly I think my issue, that `runtime->memory.mallocated` is `null` is related to a locale bug because it turns out that before my binding is called in:

```cpp
d_m3Op  (CallRawFunction)`{
  // ...
  assert(runtime->memory.mallocated);
  m3ret_t possible_trap = call (runtime, &ctx, sp, mem_data);
  // ...
}
```

the assertion that `runtime->memory.mallocated` is set, always succeeds.
However if my binding is called right after, the `runtime->memory.mallocated` field is null:

```cpp
void const* my_binding(IM3Runtime runtime, IM3ImportContext _ctx, uint64_t* _sp,
                       void* _mem) {
  assert(runtime->memory.mallocated); // Fails
```

The code that MSVC has generated here seems fine and also I'm unsure by now why the value of `M3Runtime` differs across the call boundary. I'm closing this until I figured it out.
