### ISSUE TITLE
Invalid execution of optimized smallpt binary

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#218]
`./wasm3 smallpt-ex.wasm 4 32 | sha1sum`
Produces (correctly) `ea05d85998b2f453b588ef76a1256215bf9b851c`

However if `smallpt-ex.wasm` is build with `-O3` or `-Os` flags, it produces wrong output.
With `-O2` or `-Oz`, it works as expected. They all execute fine in `wasmer`.

Pre-built binaries: [smallpt.zip](https://github.com/wasm3/wasm3/files/6200583/smallpt.zip)

**Comment by vshymanskyy** [comment]
Debug build produces this error:
```log
Assertion failed at ../source/m3_compile.c:302 : o->m3Slots [i_slotIndex]
```

**Comment by vshymanskyy** [comment]
Looks related to this PR: https://github.com/wasm3/wasm3/pull/175

**Comment by vshymanskyy** [comment]
After reverting #175 things are better, but `-Os` build still fails:
```log
ea05d85998b2f453b588ef76a1256215bf9b851c  out-O2.ppm
ea05d85998b2f453b588ef76a1256215bf9b851c  out-O3.ppm
b25e6e933fef1ac856e32775706c2ec1dab22ec5  out-Os.ppm
ea05d85998b2f453b588ef76a1256215bf9b851c  out-Oz.ppm
```

**Comment by vshymanskyy** [comment]
Also in this example wasm3 fails with `[trap] invalid conversion to integer`, but it doesn't happen on browser engines.
[music-bug.zip](https://github.com/wasm3/wasm3/files/6267877/music-bug.zip)

The zip file contains execution traces of `wasm3` and `nodejs` for comparison.

Steps:

```log
➜ ./wasm3 --repl
wasm3> :load music.wasm
wasm3> :set-global SAMPLERATE 1024
wasm3> :get-global SAMPLERATE
1024.000000:f32
wasm3> playEventsAndFillSampleBuffer
==== wasm backtrace:
  0: 0x0039ca - .unnamed!<unnamed>
  1: 0x003a7e - .unnamed!<unnamed>
  2: 0x0028f4 - .unnamed!<unnamed>
  3: 0x002e01 - .unnamed!fillSampleBuffer
  4: 0x003693 - .unnamed!playEventsAndFillSampleBuffer
Error: [trap] invalid conversion to integer ()
```

**Comment by soundandform** [comment]
Made some progress figuring this out. With some tweaking, i can achieve a successful hash on all but I still haven't tracked down the cause of failure.

**Comment by vshymanskyy** [comment]
@soundandform I can confirm it also fixes the music bug.
@petersalomonsen We can now play your midisynth example 🥳

**Comment by vshymanskyy** [comment]
@soundandform but it also breaks some other examples from `pywasm3` 😢

**Comment by soundandform** [comment]
> @soundandform but it also breaks some other examples from `pywasm3` 😢

@vshymanskyy taking a quick look at pywasm code, this is probably due to the change of call frame, preparing for multi-return. empty slots (= to return count) need to be padded before args.

**Comment by vshymanskyy** [comment]
oops. will re-check!

**Comment by petersalomonsen** [comment]
Awesome that you now can play the midisynth 😀

**Comment by vshymanskyy** [comment]
@soundandform please check `pygame-maze.py` example. This one fails with `[trap] invalid conversion to integer`. it's not related to arguments conversion, as this example only runs a single `void(void)` function.
Also, pywasm3 uses only the public Wasm3 API (those `put_arg_on_stack` and `get_arg_from_stack` functions are aptly named).

**Comment by vshymanskyy** [comment]
@soundandform nevermind, figured it out. The issue was on `pywasm3` side, in the generic `RawFunction` handler.

**Comment by vshymanskyy** [comment]
I think we can close this, all of the found issues were covered by tests
