### ISSUE TITLE
cpp use of m3_CallArgv vs m3_Call

### ISSUE THREAD

**Issue by jeremyong** [wasm3/wasm3#219]
In `wasm3_cpp.h` ([link](https://github.com/wasm3/wasm3/blob/15d05ccc0d981492b75b7d557351ad1fb03f42b3/platforms/cpp/wasm3_cpp/include/wasm3_cpp.h#L342)), arguments to a function are (expensively) converted to `std::string` before being passed to `m3_CallArgv` afterwards they are being converted back. Can this not just use `m3_Call` directly passing an array of pointers at this point?

The example works if I change the code to the following snippet below for example:

```cpp
        template<typename Ret, typename ... Args>
        Ret call(Args... args) {
            std::array<void const*, sizeof...(Args)> argv = { reinterpret_cast<void const*>(&args)... };
            M3Result res = m3_Call(m_func, sizeof...(args), argv.data());
            detail::check_error(res);
            Ret ret;
            /* FIXME: there should be a public API to get the return value */
            auto sp = (detail::stack_type)m_runtime->stack;
            detail::arg_from_stack(ret, sp, nullptr);
            return ret;
        }
```

**Comment by igrr** [comment]
Thanks for the suggestion @jeremyong. Yes, we an use m3_Call now. It didn't exist when the cpp wrapper was written. We also have a way to get the return value from the stack now (`m3_GetResults`), which resolves the remaining FIXME in this function.
I'll open a PR with these changes.
