### ISSUE TITLE
Sign-extension opcodes

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#22]
https://github.com/WebAssembly/sign-extension-ops

**Comment by vshymanskyy** [comment]
Test script is now prepared to run tests for this proposal:
```sh
./run-spec-test.py ./proposals/sign-extension-ops/*.json
```

**Comment by abalkin** [comment]
@vshymanskyy -  I would like to tackle this issue, but I cannot find the `proposals/` subdirectory under `test/` (next to the `run-spec-test.py` script.  Should I run

```
$ ./run-spec-test.py ../build/proposals/sign-extension-ops/*.json
```

instead?

**Comment by vshymanskyy** [comment]
When you run the script for the first time, it should sownload those directories

**Comment by vshymanskyy** [comment]
@abalkin let me know it it doesn't or you run into some issues

**Comment by abalkin** [comment]
Got it.  The problem was that I ran the test script from the build directory.  Maybe it should not use cwd and place everything relative to its own location.  Just a suggestion - it makes sense to `cd test` to run the test scripts.

**Comment by abalkin** [comment]
# Summary

To support sign-extending, five new sign-extension operators are added:

* [ ] i32.extend8_s: extend a signed 8-bit integer to a 32-bit integer
* [ ] i32.extend16_s: extend a signed 16-bit integer to a 32-bit integer
* [ ] i64.extend8_s: extend a signed 8-bit integer to a 64-bit integer
* [ ] i64.extend16_s: extend a signed 16-bit integer to a 64-bit integer
* [ ] i64.extend32_s: extend a signed 32-bit integer to a 64-bit integer

**Comment by abalkin** [comment]
The code that I submitted as #73, passes `proposals/sign-extension-ops` tests:

```sh
$ ./run-spec-test.py proposals/sign-extension-ops/*.json
When using fp display format, values are compared loosely (some tests may produce false positives)
Wasm3 v0.4.5 (Jan 26 2020 17:52:22, 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16), x86_64)
Running proposals/sign-extension-ops/i32.json
Running proposals/sign-extension-ops/i64.json
{'crashed': 0,
 'failed': 0,
 'missing': 0,
 'skipped': 0,
 'success': 756,
 'timeout': 0,
 'total_run': 756}
=======================
 756/756 tests OK
=======================
```

Now I need to figure out how to make these tests run in CI.

**Comment by vshymanskyy** [comment]
Merged
