### ISSUE TITLE
AttributeError: 'wasm3.Module' object has no attribute 'gasLimit'

### ISSUE THREAD

**Issue by Kuper007** [wasm3/wasm3#221]
I was trying to run your python example for gas metering (02-metered.py). Got "AttributeError: 'wasm3.Module' object has no attribute 'gasLimit'". When I looked into the m3module.c. I truly haven't found any attribute with this name. But I found `Module_setGasLimit` and `Module_getGasUsed` methods. The main issue is that I can't find access to these methods. I think the reason is that the names of these methods are missing `M3` as in the other methods that I have access to: `M3_Module_link_function`.

**Comment by vshymanskyy** [comment]
You need to install the latest pywasm3 from the main branch
