### ISSUE TITLE
Add Windows build for `wasm3-strace`

### ISSUE THREAD

**Issue by cjohnson57** [wasm3/wasm3#226]
I tried to download wapm and run the command through there, but it gives a file not found error, trying both giving the exact path to the wasm file and just having it in the same folder: https://i.imgur.com/QdaqyPp.png

I also tried just downloading the windows .exe, and I can get wasm3 to run normally there and give an output correctly, but as far as I can tell there's no way to trace with the .exe

**Comment by vshymanskyy** [comment]
It's most probably a `wapm` issue.
Can you try using `webassembly.sh` console?
If not, you need to build `wasm3-strace` on windows. Just set `-DDEBUG -Dd_m3EnableStrace=2 -Dd_m3RecordBacktraces=1` flags

**Comment by vshymanskyy** [comment]
I think we can add a windows build for future releases.

**Comment by cjohnson57** [comment]
The Windows build would be convenient. I'll try the other methods you mentioned tonight. Thank you!

**Comment by vshymanskyy** [comment]
@cjohnson57 here's a prebuild: [wasm3-strace.zip](https://github.com/wasm3/wasm3/files/6325391/wasm3-strace.zip)

**Comment by cjohnson57** [comment]
Thanks so much!
