### ISSUE TITLE
Failure running minimal Swift module

### ISSUE THREAD

**Issue by yonihemi** [wasm3/wasm3#227]
Trying to run a minimal [SwiftWasm](https://swiftwasm.org/) WASI module fails with:
```
Error: [Fatal] repl_load: invalid length UTF-8 string
Error: invalid length UTF-8 string
```
The same module runs successfully in Wasmer and WasmTime.

[hello.wasm.zip](https://github.com/wasm3/wasm3/files/6356081/hello.wasm.zip)

## Steps to create minimal executable
- Install a [recent snapshot SwiftWasm toolchain](https://github.com/swiftwasm/swift/releases)
- Create Swift file:
```sh
echo 'print("hello world")' > hello.swift
```
- Build with toolchain:
```sh
swiftc ./hello.swift -target wasm32-unknown-wasi -o hello.wasm
```
- [Detailed setup](https://book.swiftwasm.org/getting-started/setup.html)

**Comment by kateinoigakukun** [comment]
I think there are some big strings in "name" section due to C++ template expansion. So stripping all custom sections by wasm-strip would make it work.

@vshymanskyy BTW this restriction is intended to improve runtime performance?

**Comment by vshymanskyy** [comment]
Yes, it's just a matter of default settings. 
BTW, did you try the main branch, or the latest Wssm3 release?

**Comment by yonihemi** [comment]
I was trying with the version from Homebrew. Now trying from main seems to work also without stripping.

**Comment by vshymanskyy** [comment]
Ok, so this is already fixed. We've started preparing the 0.5.0 so it should land in Homebrew in a few weeks
