### ISSUE TITLE
Support for "Threads Proposal for WebAssembly"

### ISSUE THREAD

**Issue by dumblob** [wasm3/wasm3#229]
Newbie here.

Does wasm3 support the [Threads Proposal](https://github.com/WebAssembly/threads )? If it doesn't are there any plans to support it?

Any other WASM proposals which wasm3 supports and which are still only proposals (though implemented in the wild - e.g. in web browsers - for quite some time alread) and not part of the main WASM standard?

**Comment by vshymanskyy** [comment]
Threads is not implemented, and not on our roadmap yet:https://github.com/wasm3/wasm3#advanced-features-and-post-mvp-proposals-support
