### ISSUE TITLE
Multi-values support

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#23]
https://github.com/WebAssembly/multi-value

**Comment by vshymanskyy** [comment]
Test script is now prepared to run tests for this proposal:
```sh
./run-spec-test.py ./proposals/multi-value/*.json
```

**Comment by vshymanskyy** [comment]
I have implemented the `multi-value` module parsing. The main changes are:
- `FuncType` can now contain multiple return types
- Blocks are generalized to have a `FuncType`, so can have multiple args/return values

Next steps would (roughly) be:
  - [ ] Adjust `app` and `run-spec-test` script to handle multiple returns
  - [ ] Allow switching spec tests to `Wasm 1.1` easily
  - [ ] Add support for block input args
  - [ ] Replace `GetSingleRetType` usage with proper stack handling
  - [ ] Support multiple returns for `RawFunction`s
  - [ ] [maybe] Support multiple returns for `opcode`s

**Comment by vshymanskyy** [comment]
Switching the spec test version is more easy now:
```sh
cd ./test
rm -rf ./core ./proposals 
./run-spec-test.py --spec=opam-1.1.1
```
This will download the `opam-1.1.1` tests (which include `multi-value` already), and run them.
**Note:** Once it downloads the tests, `spec` argument is no longer used, so you have to remove `core`, `proposals` directories manually to switch between spec versions.

**Comment by vshymanskyy** [comment]
@soundandform Test harness was updated to support multi-values.
```sh
# fetch and run opam-1.1.1 tests:
./run-spec-test.py --spec=opam-1.1.1
# run a single test:
./run-spec-test.py .spec-opam-1.1.1/core/block.json --line 404
```
Outputs:
```log
 ----------------------
Test:     block.wast:404 block.0.wasm break-multi-value()
Args:     
Expected: result 18:i32, 4294967278:i32, 18:i64
Actual:   result 18:i32, 18:i32, 18446743992105173011:i64
=======================
 FAILED: 100.00%
=======================
```

**Comment by soundandform** [comment]
returns are now reserved 64-bit slots at the bottom of the call stack. args must be written after/above these slots.  I've updated the m3ApiReturnType macro and other m3_Call functions to work appropriately but probably missed a case.  still only one return supported.

**Comment by soundandform** [comment]
`./run-spec-test.py --spec=opam-1.1.1` now passing

**Comment by vshymanskyy** [comment]
`opam-1.1.1` is now default.
