### ISSUE TITLE
Imported functions not called after 1st exported function invocation in WASI module

### ISSUE THREAD

**Issue by yonihemi** [wasm3/wasm3#231]
Hi!

I'm attempting to load a WASI module and repeatedly call different functions from it.

The 1st call works as expected, but the issue is starting with 2nd function call (and subsequent ones) - the linked WASI functions are not called (nor are other imports).

I've tried re-linking imports (calling `m3_LinkWASI` again) which didn't help.
It's the same issue if I start with invoking `_start` or if I call any other exported function - 1st call is fine, 2nd and up not.

Tracking function calls with `d_m3EnableStrace`=1 shows WASI calls are not called after 1st invocation.

Made a [minimal reproducing code](https://github.com/yonihemi/wasm3_longrun),
<details>
  <summary>it produces this trace:</summary>
  
  ```
    Wasm3 v0.4.9 (x86_64)
    Build May  8 2021 18:13:17
    Device: x86_64

    >Loading WebAssembly...
    >Calling getNum... 
    wasi_unstable!fd_fdstat_get(1, 69672) = 0
    In getNum, returning 101
    wasi_unstable!fd_write(1, 69680, 2, 69676) = 0
    >Result: 101
    >Calling getNum... 
    >Result: 102
    Program ended with exit code: 0
  ```
  
  - Before **>Result: 102**, there should be `In getNum, returning 102` printout from the function.

</details>

Would appreciate any pointers on how to correctly achieve this.

**Comment by vshymanskyy** [comment]
@yonihemi there's definitely something with your example, as I can do this:
![image](https://user-images.githubusercontent.com/1506708/117722422-b65d5b80-b1e9-11eb-8e45-c542871b7308.png)

**Comment by vshymanskyy** [comment]
@yonihemi running your example produces:
```log
Wasm3 v0.4.9 (x86_64)
Build May 10 2021 23:54:28
Device: x86_64

>Loading WebAssembly...
>Calling _start... 
Hello, world! num is currently 100
>Calling getNum... 
In getNum, returning 101
>Result: 101
>Calling getNum... 
In getNum, returning 102
>Result: 102
```

Everything looks good. Are you sure you're using the latest `main` branch?

**Comment by yonihemi** [comment]
@vshymanskyy  could we re-open this, as it is reproducible with simple WASI?
I'm still seeing the issue even with UVWASI, but in more complex settings which I'm not managing to simplify enough to a simple project. I think if we figure this one out it will be solved as the symptom is the same.

**Comment by vshymanskyy** [comment]
Sure!

**Comment by vshymanskyy** [comment]
@yonihemi actually it's related to buffering. that wasm performed by your wasm module itself. There was no issue in wasm3.

Simple WASI implementation is by no means complete, and it didn't report `fs_rights_base` correctly in `fd_fdstat_get`.
Your module thought STDOUT was just a regular file, not a TTY: https://github.com/WebAssembly/wasi-libc/blob/659ff414560721b1660a19685110e484a081c3d4/libc-bottom-half/sources/isatty.c

I added a small workaround for this, however we do not intend to further fix/support the simple wasi implementation.
PRs are welcome anyway ;)
