### ISSUE TITLE
Assertion failed at ../source/m3_compile.c:318

### ISSUE THREAD

**Issue by sinkingsugar** [wasm3/wasm3#232]
Used to work fine a few months ago but now with the same WASI built .wasm I'm getting a lot of "no operation found for opcode" for opcode 0x36, sadly cannot run that binary on debug due to overflows.

**Comment by sinkingsugar** [comment]
Weird.. that's simply `i32.store`.

**Comment by sinkingsugar** [comment]
Consider that I run it thru a customized WASI environment but should work fine with uvwasi or so I think.

**Comment by soundandform** [comment]
@sinkingsugar I haven't gotten an opportunity to try this. But, one thought: the biggest recent change I made was adding multivalve support which ended up changing the stack frame (args & return) for function calls.  Maybe this affected your custom wasi implementation and is causing memory corruption?   

https://github.com/wasm3/wasm3/blob/3dbf3a6ded0aa8ded3b8615bf515aa0bf43bb531/source/wasm3.h#L230-L233

**Comment by sinkingsugar** [comment]
@soundandform thanks, I just double checked and seems fine, my WASI is just a carbon copy of the simple wasm3 wasi with some changes, it still uses the same macros and still looks identical. As far as I could see also there are no recent changes in the wasm3 repo.

**Comment by vshymanskyy** [comment]
@soundandform this also fails with `uvwasi` implementation.
In debug build I get: `Assertion failed at ../source/m3_compile.c:318 : i_slot >= o->slotFirstDynamicIndex`

Files to reproduce:
[shader.zip](https://github.com/wasm3/wasm3/files/6553644/shader.zip)

**Comment by vshymanskyy** [comment]
Also, `clang.wasm` is failing on `Assertion failed at ../source/m3_compile.c:319 : i_slot < o->slotMaxAllocatedIndexPlusOne`

**Comment by sinkingsugar** [comment]
@vshymanskyy thanks! Glad this is highlighting some regressions in general.

Maybe clang or this shader compiler should be in CI somehow as they are an example of a big full blown app.

**Comment by vshymanskyy** [comment]
@sinkingsugar Should be fixed now

**Comment by sinkingsugar** [comment]
Cool thanks!
