### ISSUE TITLE
None of scripting language interpreters work

### ISSUE THREAD

**Issue by niutech** [wasm3/wasm3#238]
I tried running various scripting language interpreters from [wapm](https://wapm.io), such as: [php.wasm](https://registry-cdn.wapm.io/contents/_/php/0.1.1/php.wasm), [lua.wasm](https://registry-cdn.wapm.io/contents/_/lua/0.1.4/lua.wasm), [python.wasm](https://registry-cdn.wapm.io/contents/_/python/0.1.0/bin/python.wasm), [rustpython.wasm](https://registry-cdn.wapm.io/contents/_/rustpython/0.1.3/target/wasm32-wasi/release/rustpython.wasm), [jsc.wasm](https://registry-cdn.wapm.io/contents/_/jsc/0.1.0/demo/jsc.wasm), [duktape.wasm](https://registry-cdn.wapm.io/contents/_/duktape/0.0.3/build/duk.wasm), but none of them run in Wasm3 0.4.9 on Windows 10 x64.

When I try to run them, I get multiple errors:
 - php.wasm, lua.wasm, jsc.wasm: `Error: [Fatal] repl_load: unallocated linear memory`
 - duk.wasm: `Error: compiling function overran its stack height limit`
 - python.wasm: `Error: missing imported function ('wasi_unstable.fd_filestat_get')`
 - rustpython.wasm: `Error: [Fatal] repl_load: file is too big`

Why can't Wasm3 interpret any of these languages? Where can I find a working wasm file of any of them? Thanks!

**Comment by vshymanskyy** [comment]
**php.wasm, lua.wasm, jsc.wasm** - those use emscripten ABI: https://github.com/wapm-packages/jsc/blob/6990dc591e5979747ea4ff652527d0c415e034d4/wapm.toml#L8-L11
Wasm3 doesn't support this (like most non browser-based engines).

**duk.wasm** probably needs increasing `d_m3MaxFunctionStackHeight` and rebuilding wasm3.

**python.wasm** fails, similar to this #232  => will investigate.

**rustpython.wasm** works with the latest version from main branch:
```sh
$ ./wasm3 --stack-size 1000000 rustpython.wasm 
Welcome to the magnificent Rust Python 0.1.1 interpreter 😱 🖖
>>>>> 1+2
3
```

**QuickJS** also works:
```sh
./wasm3 qjs.wasm 
QuickJS - Type "\h" for help
qjs > 2+5
2+5
7
```

**Comment by vshymanskyy** [comment]
I'm closing this, as all of the issues are either solved, known or can be resolved by adjusting the configuration.
