### ISSUE TITLE
Improve memory bounds checks

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#24]
Currently, memory addresses in `Load` and `Store` operations are cast to `u64` to workaround address overflow (i.e. on 32-bit platforms):
https://github.com/wasm3/wasm3/blob/e40383bc73c147ece499a7c9602a2792395457bc/source/m3_exec.h#L751-L752
There are several things we can improve here:
- [x] Find more efficient way of checking overflows, that would also work for 64-bit address space in future
- [ ] Add compile-time flag to skip those checks (i.e. for benchmarks)

**Comment by vshymanskyy** [comment]
@soundandform this context, it looks like we should pass the M3MemoryHeader around (instead of raw memory pointer). Anyway each time we access the memory, we have to do pointer arithmetic (just backwards). Then, we can include `length` instead of the end pointer, and the bounds check becomes trivial. It might even become more efficient in the end. I'll try implementing this.

**Comment by soundandform** [comment]
At some point in the past, I imagined an option to disable bounds-checking to improve performance when using a simplistic CPU & security wasn't an issue.  So that's why it's in this quirky hidden-header configuration, but I'm cool with removing this and making it more straightforward.

**Comment by MaxGraey** [comment]
For 64-bit systems you could use page guard handling btw:
https://docs.google.com/document/d/17y4kxuHFrVxAiuCP_FFtFA2HP5sNPsCD10KEx17Hz6M/edit

It's how done in wasmer, v8 and FF.

**Comment by vshymanskyy** [comment]
We can now disable linear memory and stack bounds check via `d_m3SkipMemoryBoundsCheck`, `d_m3SkipStackCheck`

**Comment by vshymanskyy** [comment]
@MaxGraey @soundandform it looks like we can get some 10% speed boost by using page guards (estimated by removing the explicit checks, running CoreMark). On some tasks, it may be even more significant, so I would consider using this at some point.
