### ISSUE TITLE
RFE: C API documentation?

### ISSUE THREAD

**Issue by FGasper** [wasm3/wasm3#245]
Hello,

Is there any formal documentation of wasm3 as a C library? How does this library compare to the “living standard” interface that Wasmer & Wasmtime expose?

Thank you!

**Comment by vshymanskyy** [comment]
1. There are some good of examples of API usage:
    - Examples in Arduino repository https://github.com/wasm3/wasm3-arduino
    - Examples in pywasm3: https://github.com/wasm3/pywasm3
    - pywasm3 implementation itself: https://github.com/wasm3/pywasm3/blob/main/m3module.c
    - And many third-party examples on github
2. There's no intention to follow the “living standard”, as we consider our API more convenient and clean (and we're getting such feedback as well) 
3. Public API is defined and described here: https://github.com/wasm3/wasm3/blob/main/source/wasm3.h
    - Wasm3 API is not stable (i.e. is subject to change esp. until version 1.0 is released), so no formal documentation.
