### ISSUE TITLE
How to run .wasm for web?

### ISSUE THREAD

**Issue by munsocket** [wasm3/wasm3#246]
For example we imported `Math.random()` function or Canvas API from JS to WASM. Can we create a glue code for iOS/Android that implements this interface so that WASM will be run correctly with iOS functions and API? It would be great to have examples like this in repo.

**Comment by vshymanskyy** [comment]
Binding native functions is simple, check out Arduino example:
https://github.com/wasm3/wasm3-arduino/blob/8e42b93557bf316e1d6752ec1cac0f4c303e1afd/examples/Wasm_Dino_PyBadge/Wasm_Dino_PyBadge.ino#L33-L43

**Comment by munsocket** [comment]
And what about audio/graphics support? Because this is the only one I am interested in. PRNG can be implemented in pure wasm easily.

**Comment by vshymanskyy** [comment]
The only way to access external functionality in WASM, is using Imported Functions. Like the one that is shown in an example. Nothing prevents those functions from drawing on screen or playing audio.

**Comment by munsocket** [comment]
This is exactly that I wanted to hear thanks, I need to try iOS and Android.
