### ISSUE TITLE
Question regarding the implementation of wasm3.

### ISSUE THREAD

**Issue by Becavalier** [wasm3/wasm3#249]
Hi team, wasm3 is really a great project, but I was wondering about the following question regarding the implementation detail of it, could someone please help clarify a little bit? Thanks!

1. How does wasm3 guarantee the compiler will do TCO (tail-call optimization) when the opcode handlers are invoked in a chain-like style? Since TCO is not a "must-done" stuff for compilers, which means in some specific cases, it may cause the stack to blast.

**Comment by vshymanskyy** [comment]
You answered your own question. Wasm3 cannot guarantee TCO, but it is the case (what actually happens) for majour compilers and architectures.
