### ISSUE TITLE
Problem Using With Arduino ESP

### ISSUE THREAD

**Issue by sfranzyshen** [wasm3/wasm3#253]
I'm having a hell of a time trying to get wasm3 working on the Arduino esp8266/esp32 platforms ... I am able to compile and run all of the code used in this [repository](https://github.com/sfranzyshen/wasm3_testing) ... separately ... but I am not able to run all of the code combined together. If I comment out some of the code in the app source code, it will work ... and if I undo the commented code and comment out some different code, it will also work ... but if I undo all the commented out code ... it fails ...  what am I doing wrong? I setup a repository of the code I used for testing and the results I have had ... https://github.com/sfranzyshen/wasm3_testing
from what I can tell ... the stack runs out ... any help would be greatly appreciated ...

**Comment by sfranzyshen** [comment]
I found this [conversation](https://ask.csdn.net/questions/6422625) and this [repository](https://github.com/onionhammer/repro-wasm3) that appear to be relate to this situation ... It's not fully clear if the problem was overcome ... or just a workaround ... but the their fix seems to required the use of a duel core ESP32 to spawn a new task ... but this wouldn't be available to ESP32s2 or Esp8266 platforms ... So does this mean I'm out of luck? Why does Wasm3 use so much "Stack" when there is still plenty of heap available ...

**Comment by igrr** [comment]
It looks like you are running wasm3 from the default task (which executes setup and loop Arduino functions). You may try creating a new task for wasm3 stuff with a larger stack size.
The reason why wasm3 needs more stack on esp32 and esp32s2 is explained here: https://github.com/wasm3/wasm3/issues/28#issuecomment-569831125. See the linked PR for more information. 
https://github.com/wasm3/wasm3/issues/241 currently tracks this problem.

**Comment by sfranzyshen** [comment]
> It looks like you are running wasm3 from the default task (which executes setup and loop Arduino functions). You may try creating a new task for wasm3 stuff with a larger stack size.
> The reason why wasm3 needs more stack on esp32 and esp32s2 is explained here: [#28 (comment)](https://github.com/wasm3/wasm3/issues/28#issuecomment-569831125). See the linked PR for more information.
> #241 currently tracks this problem.

thanks you for your response ... I will give the new task a try ... and wait for progress to come ...

**Comment by sfranzyshen** [comment]
#241 currently tracks this problem

**Comment by sfranzyshen** [comment]
After reading the following statment in this [document](https://github.com/wasm3/wasm3/blob/main/docs/Interpreter.md#stack-usage) from the wasm3 project ... I decided to try something different ... and it's working on the ESP32 and esp8266 !!

```Returning from a Wasm function also unwinds the stack, back to the point of the Call operation.```

the work around is to write the code inside the wasm app to be non blocking ... allowing the execution flow to return back to the arduino host, resetting the stack used ... **bingo!**
