### ISSUE TITLE
cpp: call exported function with no return value

### ISSUE THREAD

**Issue by arrisde** [wasm3/wasm3#256]
I'm trying to use the cpp wrapper to call a wasm-exported function which has no return value. It seems that both `function::call<...>()` and `function::call_argv<...>()` expect the type of return value as template parameter. How would I invoke these if the wasm function does not return anything?

**Comment by igrr** [comment]
I think this is not implemented. `call` probably needs to be partially specialized for the void return type,  similar to how it is done for `wrap_helper`.

**Comment by arrisde** [comment]
Thanks, I tried implementing your suggestion in #257.
