### ISSUE TITLE
Stuck on allocating unavaliable memory with Emscripten

### ISSUE THREAD

**Issue by vdimir** [wasm3/wasm3#260]
Using default allocator from Emscripten, calling `malloc` twice allocating all avaliable data, second call stuck forever.

Example to reproduce based on example from repo: https://github.com/vdimir/wasm3/blob/b0652670f1458e51c8a36289fd562c98c83cfb9f/platforms/cpp/wasm

Allocate total memory from wasm:
https://github.com/vdimir/wasm3/blob/b0652670f1458e51c8a36289fd562c98c83cfb9f/platforms/cpp/wasm/test_prog.c#L7-L18

Call this function twice:

https://github.com/vdimir/wasm3/blob/b0652670f1458e51c8a36289fd562c98c83cfb9f/platforms/cpp/main.cpp#L24-L28

First call is ok, second one will loop forever

**Comment by vshymanskyy** [comment]
I think there's a bug in your program.
I'm able to reproduce it with a REPL:
```log
$ ./build/wasm3 --repl                    
wasm3> :load test/alloc/test_prog.wasm
wasm3> allocate_test 1
Result: 0
wasm3> allocate_test 2
(hangs) ^C
```
But, you skipped to check if the memory was allocated by `malloc`, i.e:
```cpp
    char * x = malloc(n);
    if (!x) return -1;
```
After adding this line, we see that memory alloc fails:
```log
$ ./build/wasm3 --repl
wasm3> :load test/alloc/test_prog.wasm
wasm3> allocate_test 1
Result: -1
wasm3> allocate_test 1
Result: -1
wasm3> allocate_test 1
Result: -1
wasm3> 
```

OK, let's change the buffer size to 10Mb (considering TOTAL_MEMORY=32MB):
```log
$ ./build/wasm3 --repl
wasm3> :load test/alloc/test_prog.wasm
wasm3> allocate_test 1
Result: 5244440
wasm3> allocate_test 1
Result: 15730208
wasm3> allocate_test 1
Result: -1
wasm3> 
```

Looks good to me.
