### ISSUE TITLE
Crash when linking function in module without runtime ownership

### ISSUE THREAD

**Issue by JamesDunne** [wasm3/wasm3#263]
Crashed in `AcquireCodePageWithCapacity` via `LinkRawFunction` when calling `m3_LinkRawFunction` on a module that has not been loaded into a runtime.

```
IM3CodePage page = AcquireCodePageWithCapacity (io_module->runtime, 4);
```

Since `io_module->runtime` is NULL this causes a segmentation fault.

**Comment by vshymanskyy** [comment]
The crash should be avoided, however it's still an invalid API usage.

**Comment by JamesDunne** [comment]
Yup I see why but it's good to have a validation and error message for it in the api.
