### ISSUE TITLE
Multi-threading emulation

### ISSUE THREAD

**Issue by ShuP1** [wasm3/wasm3#265]
As shown in #127, proper interpreter pausing can open up impressive possibilities.

> Oh, this would also allow us to implement multi-threading emulation, i.e. running multiple wasm files on a single native thread.

As far as I know, during m3_Yield no restrictions apply other than careful interaction with the runtime.
So you could probably call another instance of the engine?

What is currently missing to make this a reality?
- [ ] Trigger m3_Yield in long loops.
- [ ] It's probably not that simple...

**Comment by vshymanskyy** [comment]
This will be possible when **Wasm Stack Switching** (or similar proposals) are implemented:
https://github.com/WebAssembly/stack-switching/blob/main/proposals/stack-switching/Overview.md
Will have to wait until then
