### ISSUE TITLE
Cross-module memory sharing

### ISSUE THREAD

**Issue by JamesDunne** [wasm3/wasm3#270]
Hi, is it possible to share memory (i.e. exchange pointers) across modules loaded in the same runtime instance?

I have a simple use case: module A calling a function in module B and passing a pointer but it fails with `callv: [trap] out of bounds memory access`. The pointer is pointing to a global in module A's memory. I was hoping the modules would share memory so I could define utility functions in module B and have this module be reusable without any knowledge of module A nor extra glue code required from the host.

If this is possible with extra glue code on the host that would be good to know how to do.

**Comment by JamesDunne** [comment]
This issue is much weirder actually.

Just adding module B to the runtime causes the `[trap] out of bounds memory access error` in module A's code that was previously working without issue and has no relation to module B. When I create a runtime with only module A loaded, everything works fine. Once I load in module B, the previously working code breaks with the trap.

In my C code I am using some large-ish global arrays but it only amounts to about 800 KiB:

```
  (global (;0;) (mut i32) (i32.const 840688))
```

**Comment by vshymanskyy** [comment]
I think this should be considered as a part of #278
