### ISSUE TITLE
Bug in c++ wrapper

### ISSUE THREAD

**Issue by skrphv** [wasm3/wasm3#271]
[platforms/cpp/wasm3_cpp/include/wasm3_cpp.h#L266](https://github.com/wasm3/wasm3/blob/main/platforms/cpp/wasm3_cpp/include/wasm3_cpp.h#L266)

1. In `wasm3::module(const std::shared_ptr<M3Environment> &env, std::istream &in_wasm)` temporary buffer `in_bytes` is created for wasm source. 
2. `in_bytes` buffer is passed to `m3_ParseModule` function
3. `in_bytes` buffer is destroyed

It leads to many different errors.  
As I understood, the buffer with wasm source have to be accessible while wasm3 works with that module.  
In [platforms/app/main.c#L110](https://github.com/wasm3/wasm3/blob/main/platforms/app/main.c#L110) in `repl_load`-function we can see that the memory is allocated for `u8* wasm` is freed if some errors occur or by call `repl_free` function. 

Making `in_bytes` buffer class variable fixes problems: 
```cpp
std::vector<uint8_t> in_bytes {};

module(const std::shared_ptr<M3Environment> &env, std::istream &in_wasm) {
    in_wasm.unsetf(std::ios::skipws);
    std::copy(std::istream_iterator<uint8_t>(in_wasm),
              std::istream_iterator<uint8_t>(),
              std::back_inserter(in_bytes));
    parse(env.get(), in_bytes.data(), in_bytes.size());
}
```

**Comment by igrr** [comment]
Thanks for reporting this @skrphv.

> As I understood, the buffer with wasm source have to be accessible while wasm3 works with that module.

Indeed I have missed [this comment](https://github.com/wasm3/wasm3/blob/067261d490a1cbcfba1471c3c31af61197aacdd8/source/wasm3.h#L218) when writing the C++ wrapper!

I think this also applies to the other constructor of `module`, where raw pointer and size are passed, the lifetime of this pointer might not be sufficiently long.

Could you please open a PR with your changes? I think @vshymanskyy can merge them quickly afterwards.

**Comment by vshymanskyy** [comment]
Merged. Thanks!
