### ISSUE TITLE
Example code for reading custom sections

### ISSUE THREAD

**Issue by InconceivableDuck** [wasm3/wasm3#284]
I'm looking for some sample code for reading [custom sections](https://webassembly.github.io/spec/core/appendix/custom.html). Any help would be greatly appreciated. Thanks!

Edit: looking closer at the code, it appears as though if the custom section is not the "name" section, they are skipped. So I suppose this issue is then a feature request to parse and expose all custom sections.

https://github.com/wasm3/wasm3/blob/85d70643593772235492140300aedff7354fd884/source/m3_parse.c#L487

**Comment by vshymanskyy** [comment]
Example usage:
```cpp
M3Result section_handler (IM3Module i_module, const char* name, const uint8_t * start, const uint8_t * end)
{
	printf("Found custom section: %s (%p .. %p)\n", name, start, end);
	return m3Err_none;
}
```
then, before calling `m3_ParseModule`:
```cpp
    m3_SetCustomSectionHandler(env, section_handler);
```

Output:
```log
Found custom section: .debug_info (0x556e5ebac34f .. 0x556e5ebad4e1)
Found custom section: .debug_loc (0x556e5ebad4ef .. 0x556e5ebadeaa)
Found custom section: .debug_ranges (0x556e5ebadebb .. 0x556e5ebae01b)
Found custom section: .debug_abbrev (0x556e5ebae02c .. 0x556e5ebae589)
Found custom section: .debug_line (0x556e5ebae598 .. 0x556e5ebaf651)
Found custom section: .debug_str (0x556e5ebaf65f .. 0x556e5ebb0248)
Found custom section: producers (0x556e5ebb0714 .. 0x556e5ebb078f)
```

**Comment by vshymanskyy** [comment]
For actual parsing, you may use `Read_utf8`, `ReadLEB_u32`, `Read_u64` etc. from `m3_core.h`

**Comment by vshymanskyy** [comment]
@InconceivableDuck did it help?

**Comment by InconceivableDuck** [comment]
Yep, this appears to be what I was looking for. Thanks! For our specific implementation (and a workaround), we also added the same information to globals, which worked well.
