### ISSUE TITLE
No example for float handling in call return / arguments

### ISSUE THREAD

**Issue by benkuper** [wasm3/wasm3#287]
Hello (again),
it seems that floats are very peculiar to work with in this environment..
I managed to pass a float to a function call but I can't seem to be able to return a float from a call:

WASM script > call C++ getNumber():float > not receiving good.

I actually can't really debug more  than this because string handling seems like a problem as well to debug from ESP32, and doing dev.println(myFloat.toString()) makes it crash..

If you have some simple working example with float handling both ways, that would be great !
I can provide more info if need be.

**Comment by vshymanskyy** [comment]
How about this?
https://github.com/wasm3/wasm3-arduino/blob/bd0075464c7a0027d8c8f260d560ab41f80db68c/examples/Wasm_CoreMark/Wasm_CoreMark.ino#L34-L42

**Comment by benkuper** [comment]
Thank you, I had checked this and I have to look at the GetResults in details (not sure where to find the source of the wasm as it's not in the example folder).
Anyway, my problem is the other way around: what I'm looking for is from the WASM script to call a C++ function and handle floats.

I tried using the "f" type, which seems to  work, partially.

This is the linking to the functions
```
 m3_LinkRawFunction(module, arduino, "pointRGB", "v(ffiii)", &m3_pointRGB);
 m3_LinkRawFunction(module, arduino, "pointHSV", "v(ffiii)", &m3_pointHSV);
 m3_LinkRawFunction(module, arduino, "getOrientation", "f(i)", &m3_getOrientation);
 m3_LinkRawFunction(module, arduino, "getYaw", "f()", &m3_getYaw);
```

The actual functions 

```
m3ApiRawFunction(m3_pointHSV)
{
    m3ApiGetArg(float, pos);
    m3ApiGetArg(float, radius);
    m3ApiGetArg(uint32_t, h);
    m3ApiGetArg(uint32_t, s);
    m3ApiGetArg(uint32_t, v);
    MainManager::instance->leds.rgbManager.point(CHSV((uint8_t)h, (uint8_t)s, (uint8_t)v), pos, radius, false);

    m3ApiSuccess();
}



m3ApiRawFunction(m3_getOrientation)
{
    m3ApiGetArg(uint32_t, index);
    m3ApiReturnType(float);
    float v = MainManager::instance->imu.orientation[index];
    m3ApiReturn(v);
}

m3ApiRawFunction(m3_getYaw)
{
    m3ApiReturnType(float);
    m3ApiReturn(MainManager::instance->imu.orientation[0]);
}

```

And the export declaration in the app.ts file
```
export declare function pointRGB(p:f32, rad:f32, r:u32, g:u32, b:u32): void;
export declare function pointHSV(p:f32, rad:f32, h:u32, s:u32, v:u32): void;
export declare function getOrientation(i:u32): f32;
export declare function getYaw(): f32;
```

The pointRGB/pointHSV and getYaw() work, but when I call the getOrientation(index) function and check the value of the index variable, it seems that there is a big mixup as the value actually shows the millis(), which is a linked function, like in the examples, but nothing to do with the getOrientation, so I guess there is some memory access crazyness and don't really know how to debug this or where it could come from.

Since I have not seen even one code online using floats as arguments, or returning values from c++ calls, I'm wondering what types are allowed and handled by wasm3 : can I provide u8 and get them as uint8_t (and return them) or is it pointless because they will be casted as u32 anyway ?
The only signatures I find are using uint32_t

Thank you

**Comment by benkuper** [comment]
@vshymanskyy I just tested a very basic setup and here's what I found, debugging the value of the argument on the arduino side in the getOrientation() function :

 - setup using ONLY the `getOrientation(i:u32):f32` function : the argument's value is 0 
 - setup using `millis():u32` AND `getOrientation(i:u32):f32` : the argument's value in `getOrientation()` is by some magic the result of the `millis()` function. In the .ts file, the call to `millis()` is done after the `getOrientation()` and there is no link between the 2 calls, no variable sharing, just testing to call the 2 functions.
 - setup using `getThrowState():u32` and `getOrientation(i:u32):f32` : the argument's value is now `getThrowState()` result. 

I've tried changing the order of export in the .ts , swapping call orders, but it doesn't change anything. Could it be something linked to the memory mapping ?

The config is this one  :

```
#define WASM_STACK_SLOTS 2048
#define NATIVE_STACK_SIZE (32 * 1024)
#define WASM_MEMORY_LIMIT 4096
```

I'm assuming this is not intended behaviour .. ?

**Comment by benkuper** [comment]
ok my bad, this was a problem with order of calls.
I found later somewhere, that m3ApiReturnType should come before m3ApiGetArg ..
