### ISSUE TITLE
Refactoring mistake (with `d_m3EnableCodePageRefCounting` option enabled)?

### ISSUE THREAD

**Issue by skrphv** [wasm3/wasm3#288]
@vshymanskyy 
1) looks like here [m3_compile.c#L173](https://github.com/wasm3/wasm3/blob/main/source/m3_compile.c#L173) `m3ReallocArray`-function not have been changed; and have to be like next:
```cpp
_               (m3_ReallocArray (IM3CodePage, & func->codePageRefs, func->numCodePageRefs, index));
```

2) undefined function `Runtime_ReleaseCodePages`  here [m3_function.c#L131](https://github.com/wasm3/wasm3/blob/main/source/m3_function.c#L131)

**Comment by vshymanskyy** [comment]
I don't think `d_m3EnableCodePageRefCounting` is currently supported. Better to disable it for now.

**Comment by vshymanskyy** [comment]
Runtime_ReleaseCodePages was never implemented, so you can just comment it out:

https://github.com/wasm3/wasm3/blob/9f8766b9016aec1278e490cc5348605d2fec5fe4/source/m3_env.c#L35-L38

**Comment by vshymanskyy** [comment]
@soundandform probably should remove that option completely?

**Comment by vshymanskyy** [comment]
removed
