### ISSUE TITLE
RFC: add CMakeLists.txt to `source` subdirectory, make it useable as a library

### ISSUE THREAD

**Issue by igrr** [wasm3/wasm3#29]
For projects built with CMake build system, the natural way of using `wasm3` would be to call `add_subdirectory` to include wasm3 as a static library. However the root CMakeLists file contains a lot of logic related to host app builds, so it may be not suitable for the purpose.

It seems that one way to expose a static library would be to add a CMakeLists.txt file into the source directory, then add this library using `add_subdirectory` and `target_link_libraries` in the CMakeLists files which want to use this library. This is in line with the "modern CMake" approach to structuring CMake projects. It helps eliminate hacks like symlinks in platform-specific examples (at least the ones which are built using CMake).

If noone sees a problem with this, I will open a PR for such refactoring.

**Comment by vshymanskyy** [comment]
Absolutely. Actually this is in our TODO list, however we didn't get to it.

**Comment by igrr** [comment]
Have created https://github.com/wasm3/wasm3/pull/30.
