### ISSUE TITLE
Dart and Flutter Support?

### ISSUE THREAD

**Issue by justin-echternach** [wasm3/wasm3#293]
is there any intention of supporting dart and flutter like wasmer does?

I am very interested using wasm3 over wasmer because of the interpreter.  If I wanted to do this integration myself, could you point me in the right direction?

Best Regards,

Justin

**Comment by vshymanskyy** [comment]
I think this set of articles should be useful and insightful:
https://shareup.app/blog/loading-webassembly-modules-in-swift/

**Comment by justin-echternach** [comment]
Thanks ... I need to do it in dart.  Wasmer has a dart implementation.  I will look there.  Maybe I can use the IOS and Android versions I just need builds for those platforms, but I need to load and access them from Dart.

**Comment by justin-echternach** [comment]
Dart has an FFI feature for native integration

**Comment by vshymanskyy** [comment]
The most important thing needed for anything to happen in this space is for someone to volunteer to make it happen.
Wasmer may have it's own goals and budgets, but implementing bindings for all possible languages is a non-goal for Wasm3 (at least currently).
Python3 and Rust bindings are provided as good examples of such bindings, as well as many contributed bindings that you can see on the main README page. If you create Dart and/or Flutter bindings, we'll be happy to link to them.
