### ISSUE TITLE
How to use wasi-sdk

### ISSUE THREAD

**Issue by iNoak** [wasm3/wasm3#294]
Hi, there.
I want to use wasi-sdk (not uvwasi). It seems like I need to set the  environment variable “WASI_CC”.
Is there any document I can refer to? (like which wasi dependency I should pre-install,and how to prepare the environment setting)
Thank you.

**Comment by vshymanskyy** [comment]
You should refer to `wasi-sdk` docs, like: https://github.com/WebAssembly/wasi-sdk/blob/main/README.md
