### ISSUE TITLE
on cpp platform. wasm3_cpp.h can not be include.

### ISSUE THREAD

**Issue by vaptu** [wasm3/wasm3#295]
`
duplicate symbol 'wasm3::runtime::load(wasm3::module&)'
duplicate symbol 'wasm3::environment::parse_module(std::__1::basic_istream<char, std::__1::char_traits<char> >&)'
duplicate symbol 'wasm3::detail::check_error(char const*)'
duplicate symbol 'wasm3::runtime::find_function(char const*)' 
duplicate symbol 'wasm3::environment::parse_module(unsigned char const*, unsigned long)' 
`

**Comment by igrr** [comment]
Thanks for reporting, I've opened https://github.com/wasm3/wasm3/pull/296 to fix this.
