### ISSUE TITLE
Porting guides

### ISSUE THREAD

**Issue by leapofazzam123** [wasm3/wasm3#297]
I want to port Wasm3 to a bare metal platform. Is there some guides to port Wasm3 and maybe required libc functions to run bare bones Wasm3?

**Comment by vshymanskyy** [comment]
Like... just copy files and build them? It should be as easy as that (if you have enough resources to run)

**Comment by leapofazzam123** [comment]
What if the bare metal platform doesn't have a libc? I need a minimum libc required to run bare bones wasm3
