### ISSUE TITLE
What does wasm3 on v8 mean in the performance benchmark

### ISSUE THREAD

**Issue by chenmently** [wasm3/wasm3#299]
In the Simple recursive Fibonacci calculation test

                                            fib(40)
-----------------------------------------------------------------------------------------
# Intel i5-8250U x64 (1.6-3.4GHz)
Native C implementation                       0.23s
Linux                                         3.83s
Win 10                                        5.35s
**wasm3 on V8 (Emscripten 1.38, node v13.0.1)  17.98s**

What does wasm3 on v8 mean

**Comment by vshymanskyy** [comment]
as far as i remember, that was wasm3 compiled to wasm using emscripten and running on v8 (node.js)
