### ISSUE TITLE
Maybe a bug: integerDivideByZero

### ISSUE THREAD

**Issue by ERICXUCHI** [wasm3/wasm3#300]
Hello, I wanna tell an inconsistency between two similar testcases:

```c
// test1.c
#include <stdio.h>

int main(){
    int a = 9;
    int b = 0;
    int c = a / b;
    printf("%d", c);

    return 0;
}
```

```c
// test2.c
#include <stdio.h>

int main()
{
    int a = 9 / 0;
    
    printf("%d", a);

    return 0;

}

```

compile by emscripten:

`emcc test1.c -s STANDALONE_WASM=1 -o test1.js` 

 `emcc test2.c -s STANDALONE_WASM=1 -o test2.js`

then run:

`wasm3 test1.wasm`

`wasm3 test2.wasm`

here is the result:
![image](https://user-images.githubusercontent.com/57583292/147824419-83ee4817-d365-4215-a076-5276cb53d707.png)

test2.wasm should generate an error, perhaps something is wrong?

**Comment by sazzy4o** [comment]
The same behaviour occurs when ran with [wasmer](https://github.com/wasmerio/wasmer) and [wasmtime](https://github.com/bytecodealliance/wasmtime), so I don't think this is an issue with `wasm3`

It might be an issue with emscripten, but it does warn you about division by 0 when compiled, so it will likely be low priority:
```
$ emcc test2.c -s STANDALONE_WASM=1 -o test2.js
test2.c:6:15: warning: division by zero is undefined [-Wdivision-by-zero]
    int a = 9 / 0;
              ^ ~
1 warning generated.
```

I think this issue should be closed
