### ISSUE TITLE
unable to build wasm3

### ISSUE THREAD

**Issue by perillo** [wasm3/wasm3#308]
I tried to build `wasm3` as documented in [docs](https://github.com/wasm3/wasm3/tree/v0.5.0/docs)/Development.md.

 - Using `zig build`, I got an error: 
   ```
   ld.lld: error: undefined symbol: getrandom
   ```
   I have no idea why `getrandom` is not resolved.

 - Using `gcc` and `clang` I got a lot of errors like:
   ```
   source/wasm3.h:113:71: warning: ‘m3Err_trapStackOverflow’ initialized and declared ‘extern’
   113 | #   define d_m3ErrorConst(LABEL, STRING)        extern const M3Result m3Err_##LABEL = { STRING };
   ```
   I solved adding `-Wno-error.

When building with `gcc` and `clang` with the `-Wall` flag, I got several warnings about unused variables.
`gcc` additionally reported 4 warning about aliasing problems.

**Comment by vshymanskyy** [comment]
AFAIK it's a Zig issue on your machine (linux, I assume). Similar to this: https://github.com/ziglang/zig/issues/5882

**Comment by tau-dev** [comment]
For now, this can be avoided with this line in build.zig:
```diff
 pub fn build(b: *std.build.Builder) !void {
     var target = b.standardTargetOptions(.{});
+    target.abi = .musl;
```
