### ISSUE TITLE
Error: missing imported function ('wasi_snapshot_preview1.fd_filestat_set_size')

### ISSUE THREAD

**Issue by topolarity** [wasm3/wasm3#309]
Zig uses this function for `ftruncate` in its standard library, and it looks like it's not currently supported.

Other conspicuous absences include `fd_pread`, `fd_pwrite`, `path_rename`, and others.

No rush on support here - I understand this coverage is WIP. Just filing a bug report as recommended at https://github.com/wasm3/wasm3/blob/main/docs/Troubleshooting.md#error-missing-imported-function

**Comment by vshymanskyy** [comment]
fd_pread, fd_pwrite, path_rename are linked already.
