### ISSUE TITLE
Remove -w flag, clean up warnings

### ISSUE THREAD

**Issue by igrr** [wasm3/wasm3#31]
I understand that the project is moving quite quickly, so some number of warnings may be acceptable. However I've already bumped into an issue which would have been very easy to spot, would it be not for the `-w` build flag. 

I think selectively disabling certain warnings known for specific source files will be safer than disabling all the warnings for all the source files.

Opening this issue to track the clean-up and re-enabling of warnings.

**Comment by vshymanskyy** [comment]
A few days ago, I have finished cleaning the warnings, so there should be an adequate amount of leftovers. But it may differ depending on compiler/platform/architecture.
I think we can remove `-w` altogether from all targets.
