### ISSUE TITLE
build for iOS failed

### ISSUE THREAD

**Issue by leleliu008** [wasm3/wasm3#311]
```
./_deps/libuv-src/src/unix/darwin.c:190:28: fatal error: a parameter list without types is only allowed in a function definition
  void (*pIOObjectRelease)(io_object_t);
                           ^
1 error generated.
```

this project need https://github.com/vshymanskyy/uvwasi.git, https://github.com/vshymanskyy/uvwasi.git need https://github.com/libuv/libuv.git , above error is libuv's  and already fixed, I hope the author of uvwasi can update the libuv version to latest to resolve the problem.

https://github.com/libuv/libuv/issues/2975
https://github.com/libuv/libuv/pull/3106

**Comment by cjihrig** [comment]
It looks like https://github.com/libuv/libuv/pull/3106 was first released in libuv 1.42.0. uvwasi is currently using that version, so I think https://github.com/vshymanskyy/uvwasi.git just needs to be updated as well.

**Comment by leleliu008** [comment]
yes, you are right.

**Comment by vshymanskyy** [comment]
should be fixed now
