### ISSUE TITLE
RFE: WASI API support

### ISSUE THREAD

**Issue by FGasper** [wasm3/wasm3#317]
Currently `wasm3.h` lacks any indication of how a host caller can enable WASI support in wasm3. It would be great if the controls for doing this—which seem to be present in `m3_api_wasi.h`—could be made public.

Thank you!

**Comment by vshymanskyy** [comment]
Right now, refactoring this part of the project is rather low-prio.
WASI is enabled by default, with `uvwasi` implementation, and anyone with enough motivation can check how it gets initialized:
https://github.com/wasm3/wasm3/blob/3a144c0d39936b3c1e4ef5fd80933d8a01d4bc95/platforms/app/main.c#L78
