### ISSUE TITLE
the purpose of M3Runtime?

### ISSUE THREAD

**Issue by ringoz** [wasm3/wasm3#318]
While implementing WebAssembly.Module and WebAssembly.Instance via wasm3 I've had some difficulties understanding the mapping of types. At first, it looked like WebAssembly.Module can be mapped to M3Module and WebAssembly.Instance to M3Runtime.

But, it won't work, because:
- imports are linked to M3Module, not M3Runtime
- multiple M3Runtimes can't be loaded from single M3Module

Do you have an advice on how to properly implement WebAssembly.Instance via wasm3?
Looking at the API, I see the only way (suboptimal) to achieve this is to parse & compile M3Module every time for new WebAssembly.Instance, but why M3Runtime exists then?

**Comment by nem0** [comment]
Is there no way to do this (single module, multiple runtimes)? It's he only deal-breaker I have.
