### ISSUE TITLE
Wasmroutines

### ISSUE THREAD

**Issue by mfateev** [wasm3/wasm3#32]
How hard would be to add ability to execute multithreaded code (from WebAssembly app point of view) by a single system thread? Something like https://github.com/WebAssembly/design/issues/1321?

**Comment by MaxGraey** [comment]
Coroutines, fibers, green threads is usually many-to-one concurrency (no parallelism, which one to one or some hybrid like in goroutines) based on continuation / FSM. It require CFG transformations. Also coroutines, fibers and etc is high-level abstractions which not present in WebAssembly MVP. Basically WebAssembly presents only atomics and futex and hasn't pthreads, vfork, mutex and etc. You could polyfill atomics for example but futexes (atomic.wait / atomic.notify) should require complex CFG transformations to some sort of FSM for simulate on single thread without blocking execution.

**Comment by mfateev** [comment]
My idea is that coroutines and fibers, etc, should not be part of the wasm high level abstrations. The wasm abstraction is threads and futexes. It is the container implementation choice to not to implement real multithreading, but use stackful coroutines to run them. There are dozens of libraries implementing stackful coroutines, so I don't think it requires CFG transformations and FSMs.

**Comment by MaxGraey** [comment]
WebAssembly hasn't shadow stack, so you can't implement sackful coroutines

**Comment by soundandform** [comment]
I've thought about this a little bit previously. Coroutines/fibers could be implemented entirely within the compiled Wasm domain as-is. But it would probably be a complicated pain -- but not one we'd have to deal with personally.  Regardless, my gut says: it would be much easier, more straightforward and also facilitate tracing/debugging if fibers existed outside of Wasm code, in the runtime (whether that's interpreted or not.) I think this is what your (@mfateev) getting at.  I think this could be fairly easy.  Create a set of exported APIs: CoroutineStart ("FunctionName"), CoroutineYield (), etc. The runtime would be responsible for linking these to the outside world -- creating actual fiber and performing the context switches (using boost::context or similar).  Maybe these calls could eventually become dedicated Wasm opcodes.

**Comment by mfateev** [comment]
@soundandform My proposal is to use existing atomic.* opcodes as from the Wasm domain there is no really difference if threads are system or green ones.

**Comment by unicomp21** [comment]
Has anyone compiled boost fibers w/ emscripten yet?  To show a working demo?

**Comment by jeffRTC** [comment]
@unicomp21 Were you able to use Boost Fibers with Emscripten?

**Comment by unicomp21** [comment]
No, currently hoping for a coawait option.
