### ISSUE TITLE
Answers to questions in the README.md

### ISSUE THREAD

**Issue by sunfishcode** [wasm3/wasm3#33]
Hello, I was reading the README.md and saw the [Thoughts & Questions about WebAssembly section](https://github.com/wasm3/wasm3/blob/master/source/README.md#thoughts--questions-about-webassembly) asking for some answers.

>  Linear memory: Modules seem hardcoded to request 16MB of memory. What? Why?

This is just the default settings of the toolchain produced the modules. Most toolchains have flags for changing the memory size.

> As the host, where can I safely allocate things in linear memory? Who's in charge of this 16MB?

In general, you can't. The application is in charge, and hosts shouldn't make any assumptions about how applications manage their memory. Often the way to avoid needing to do this is to ask the application to do an allocation, and pass the VM a pointer to it.

> Traps: The spec says "Signed and unsigned operators trap whenever the result cannot be represented in the result type." Really? That's cool, but how can the behavior of source languages be modeled (efficiently)? C integer operations wrap and sometimes that's what you want.

It's admittedly subtle, but wasm's `add`, `sub`, and `mul` aren't considered signed or unsigned, so that rule doesn't apply to them and they wrap rather than trap.

**Comment by vshymanskyy** [comment]
Dan, thanks for explanations, this is really helpful!
Currently there's also another question that bothers me a lot.
WebAssembly page is defined to consist of 65,536 bytes. On the other side, many embedded platforms can only afford to allocate 32..48 Kb of linear memory. Currently, we can intoduce some workarouns (i.e. allocate as much memory as we can, and trap on OOB access), but I'm wondering if this issue is going to be addressed by WebAssembly standard. I'm aware that **Large page support** is considered for 🦄 future, but how about small pages? ;)

**Comment by sunfishcode** [comment]
There have been a [few discussions](https://github.com/WebAssembly/spec/issues/899) of smaller page sizes, but I don't know of anyone working on a proposal yet.

**Comment by soundandform** [comment]
Yes, thanks for info!  Makes sense about memory allocation.  Would be nice if this was formalized into the Wasm compilation model. A hack I've considered is placing all runtime-allocated resources at negative offsets.

**Comment by vshymanskyy** [comment]
@sunfishcode I'm closing the ticket, but we can still raise some question here in future.
BTW, you can enjoy the initial Wasm3 release: https://github.com/wasm3/wasm3/releases/tag/v0.4.2
Thanks a lot!

**Comment by vshymanskyy** [comment]
@sunfishcode another interesting question here: https://github.com/WebAssembly/spec/issues/899#issuecomment-578231748

**Comment by sunfishcode** [comment]
And it's now been answered.
