### ISSUE TITLE
Does wasm3 support linux?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#338]
Does wasm3 support linux? And how to use install wasm3 in linux?

**Comment by sfranzyshen** [comment]
Yes, It's stated in the status on the main page ...
https://github.com/wasm3/wasm3#status

**Comment by Zhangyx24** [comment]
@sfranzyshen Thanks for your answer!
Does wasm3 only support OpenWrt in linux?
Does wasm3 support ubuntu?

**Comment by vshymanskyy** [comment]
https://github.com/wasm3/wasm3/releases/latest

![IMG_20220624_083719](https://user-images.githubusercontent.com/1506708/175469562-ed609276-7b75-4fa4-b7af-6ee60afc07d3.jpg)

**Comment by Zhangyx24** [comment]
Thanks a lot!
