### ISSUE TITLE
Easy embedding in other programs

### ISSUE THREAD

**Issue by prabirshrestha** [wasm3/wasm3#34]
I have been trying to embed WASM in vim as default. I had send one PR on embedding JS to vim https://github.com/vim/vim/pull/5198.

Is it possible to just have 2 files `wasm3.h` and `wasm3.c` in the output similar to how [duktape](https://duktape.org/) does it to make it easy to embed in other programs? This way I can just `#include "wasm3.h"` and don't have to worry about it.

**Comment by vshymanskyy** [comment]
Nice idea. I think it should be possible.
Right now it's also quite easy to embed the library (by including all the files), but we will trh improving that once the API is more stable.

**Comment by prabirshrestha** [comment]
I was trying to make the same changes as in ECMAScript duktape support in vim and gave up after 2 hour of trying. The biggest issue with C programs are that each repo has its own way of compiling so rather then trying to prototype WASM in vim it I spent too much time on the vim build system just to make it compile.

**Comment by vshymanskyy** [comment]
@prabirshrestha I agree, but it looks like a problem of vim build system. Almost all of the [platforms](https://github.com/wasm3/wasm3/tree/master/platforms) are just symlink to the wasm3 `source` directory. Including a single file is only a slight improvement (IMHO).
Could you elaborate on the spceific problem you faced (scenarios, logs), then we can decide if (and what) can be improved.

P.S. Also, some build systems enable `-Werror` by default. This creates problems when embedding `wasm3`. It's currently not documented how to deal with this.

**Comment by vshymanskyy** [comment]
@prabirshrestha could you provide more info on this? Thx

**Comment by prabirshrestha** [comment]
I have pushed by branch. Which can be found at https://github.com/prabirshrestha/vim/tree/wasm-build.

Currently you need linux or mac since win builds for vim are completely different.

```sh
./configure --enable-wasminterp
make
```

Currently failing with.

```
make[1]: *** No rule to make target `src/wasm/source/m3.h', needed by `objects/m3_api_libc.o'.  Stop.
make: *** [first] Error 2
```

Most likely I have done something stupid.

Currently my goal is to just make sure compilation is working and it is embedding wasm3 in vim and then next is to slowly expose wasm apis to vim.
