### ISSUE TITLE
Does wasm3 support execution of SIMD?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#346]
Does wasm3 support execution of SIMD?
Waiting for your answer.
Thanks a lot.

**Comment by Rochet2** [comment]
Take a look at the features table on the main readme page:
https://github.com/wasm3/wasm3#features
Currently the box for Fixed-width SIMD is not ticked.

**Comment by Zhangyx24** [comment]
I use wasm3 to run a wasm from a wat file with simd instructions:
(module
  (type (;0;) (func))
  (func $func1 (;0;) (type 0)
    v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000
    i64x2.extend_low_i32x4_u
    v128.const i32x4 0x00000000 0x00000000 0x00000000 0x00000000
    i64x2.mul
    i32x4.all_true
    i64.load offset=1 align=1
    drop)
  (func $func2 (;1;) (type 0)
    nop)
  (memory (;0;) 5613 17832)


  (export "func1" (func $func1))
  (export "func2" (func $func2))

  (start $func1)
)

but failed with:
Error: unknown opcode (opcode 'fd' not available) on macOS
and Illegal instruction (core dumped) on ubuntu

Does it means that simd is not supported yet?

**Comment by vshymanskyy** [comment]
SIMD is not planned atm, however contributions are welcome

**Comment by Zhangyx24** [comment]
Thanks for your reply !
