### ISSUE TITLE
add support for WASM C api

### ISSUE THREAD

**Issue by prabirshrestha** [wasm3/wasm3#35]
This will allow us to easily embed in other programs and swap the runtimes without learning specific.

https://github.com/WebAssembly/wasm-c-api

**Comment by vshymanskyy** [comment]
Thanks, we know about this approach and may consider it in future. But currently it's not our goal.

**Comment by vshymanskyy** [comment]
BTW, wasm-c-api is full of it's own issues, and some of them are a no-go for `Wasm3` at the moment.
