### ISSUE TITLE
File is too big ?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#350]
When executing a wasmfile which is 72MB, the wasm3 prints :
Error: [Fatal] repl_load: file is too big
Error: file is too big

Is there any limit for wasm3 to load wasm file?

**Comment by vshymanskyy** [comment]
Increased to 256 MB: https://github.com/wasm3/wasm3/blob/7890a2097569fde845881e0b352d813573e371f9/platforms/app/main.c#L129
