### ISSUE TITLE
repl_load: unknown value_type ?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#352]
## Steps to reproduce 

The wat file :

(module
    (type (;0;) (func (param externref) (result i32)))
    (func $test (type 0) (param externref) (result i32)
        (local i32)
        i32.const 0
        local.tee 1
        i32.const 0
        i32.eq
        if
        else
        end
        local.get 1
        local.get 0
        table.set 0
        local.get 1
    )
    (table (;0;) 4 externref)
    (export "test" (func $test))
)

`wat2wasm test.wat`
`wasm3 test.wasm`

## Expected result
successfully load the module

## Actual result
Error: [Fatal] repl_load: unknown value_type
Error: unknown value_type

**Comment by vshymanskyy** [comment]
`Reference Types` are not supported yet: https://github.com/wasm3/wasm3#features
