### ISSUE TITLE
<Empty Stack> ？

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#354]
## Steps to reproduce

When executing the wasm file, the wasm3 0.5.0 prints Result: <Empty Stack>
Is it a bug ?

[test.txt](https://github.com/wasm3/wasm3/files/9230427/test.txt)

Execute the `multiply_4` function and `multiply_8` function in macOS or ubuntu.
`wasm3 --func multiply_4 test.wasm` and ``wasm3 --func multiply_8 test.wasm``

## Expected result
Successfully load and excute the 2 functions.

## Actual result
The wasm3 prints : 
```
Result: <Empty Stack>
```

**Comment by vshymanskyy** [comment]
`<Empty Stack>` means that function did not return any values.
Which is correct for `multiply_4` and `multiply_8` functions in your `test.wasm`
