### ISSUE TITLE
Fail to rename file ?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#355]
## Steps to reproduce
Trying to rename the oldfile name to newfile through the test.wasm.
The wasm file is uploaded as test.txt.
[test.txt](https://github.com/wasm3/wasm3/files/9230640/test.txt)

The wasm file is compiled from a C program:
[main.txt](https://github.com/wasm3/wasm3/files/9230647/main.txt)

## Expected result
change the file oldfile to name newfile.
And other wasm runtime, including wasmer, wasmtime, wasmedge, WAMR could successfully do this.

## Actual result
Assertion failed: oldfile != NULL (main.c: main: 9)
Error: [trap] unreachable executed

**Comment by vshymanskyy** [comment]
Fixed by https://github.com/wasm3/wasm3/pull/328
