### ISSUE TITLE
Directories with more than ~150 files are truncated when mapped ?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#357]
## Steps o reproduce

This is related to https://github.com/bytecodealliance/wasmtime/issues/2493
Compile the C program into wasm :
[ls.txt](https://github.com/wasm3/wasm3/files/9233767/ls.txt)

 `wasm3 ls.wasm --dir=./testfolder -- testfolder | wc -l`

## Expected result
203

## Autual result
0

## Environment
wasm3 0.5.0
The problem both occur on macOS and ubuntu.

**Comment by vshymanskyy** [comment]
Reported here: https://github.com/wasm3/wasm3/issues/357
