### ISSUE TITLE
`out of bounds memory access` error ?

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#358]
## Steps to reproduce
[test-wat.txt](https://github.com/wasm3/wasm3/files/9234430/test-wat.txt)
[test-wasm.txt](https://github.com/wasm3/wasm3/files/9234431/test-wasm.txt)

The test.wasm is uploaded as test-wasm.txt, and test.wat is uploaded as test-wat.txt

`wasm3 test.wasm`

## Expected result
Print "TEST"
Other wasm runtime, incuding wasmer, wasmtime, WAMR could print "TEST" successfully.

## Actual result
Error: [trap] out of bounds memory access

**Comment by vshymanskyy** [comment]
@Zhangyx24 could you please re-test it with the latest version from `main` branch? Cannot reproduce it anymore
