### ISSUE TITLE
Unable to load module ？

### ISSUE THREAD

**Issue by Zhangyx24** [wasm3/wasm3#361]
## Steps to reproduce
[test-wat.txt](https://github.com/wasm3/wasm3/files/9276749/test-wat.txt)
[test-rs.txt](https://github.com/wasm3/wasm3/files/9276751/test-rs.txt)
test.rs is uploaded as test-rs.txt and test.wat is uoloaded as test-wat.txt.
Call the host functions `assert_eq_i32` and `print_input` in wasm.
`cargo run --example test-wasmer2721`

## Envrionment
wasm3 0.5.0
macOS10.15 and ubuntu20.04

## Expected result
Print_input_host 6513249
equals i32 !
Print_input_host 1819043176
equals i32 !
Print_input_host 1819043176
Print_input_host 1685024583
Print_input_host 1685024583
Print_input_host 3355185

## Actual result
Start testing ...
thread 'main' panicked at 'Unable to load module: Wasm3("missing imported function")', test.rs:15:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by vshymanskyy** [comment]
`assert_eq_i32` and `print_input` functions are not available in the host environment, hence the `missing imported function` error. This is expected.

**Comment by Zhangyx24** [comment]
Thanks a lot for your reply! 
Could you please give me an example of importing host functions in the rust api? I go through the examples in the wasm3-rs project, but didn't find any example about this usage.
