### ISSUE TITLE
On Windows, failed to run custom build command for `wasm3-sys v0.3.0`.

### ISSUE THREAD

**Issue by abc767234318** [wasm3/wasm3#369]
Add following to Cargo.toml.
```
[dependencies]
wasm3 = "0.3.1"
wasm3-sys = "0.3.0"
```
Output following:
```
error: failed to run custom build command for `wasm3-sys v0.3.0`
```

**Comment by vshymanskyy** [comment]
Please see https://github.com/wasm3/wasm3-rs/issues/1#issuecomment-1223499924 (and [reply](https://github.com/wasm3/wasm3-rs/issues/1#issuecomment-1223646664))
