### ISSUE TITLE
GoLang bindings

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#38]
Implement Go bindings, so `wasm3` can be easily used from Go.

**Comment by matiasinsaurralde** [comment]
First steps: https://github.com/matiasinsaurralde/go-wasm3

Cheers! 😃

**Comment by matiasinsaurralde** [comment]
Btw, the above Go repo uses [this CMake tweak](https://github.com/matiasinsaurralde/wasm3/commit/824cb245617ad9888e1b36c47c164d5c687cd272), which seems related to #29. I will adapt it to whatever ends up on your `master`, for now I've provided some pre-built static libraries, just like `wasmer` does for its Go extension.

**Comment by vshymanskyy** [comment]
@matiasinsaurralde thanks. You're right, CMake will be refactored soon.
Also, let us know if you need us to extend the API, i.e. #41

**Comment by matiasinsaurralde** [comment]
Memory access working (can be improved but it's a good start!): https://github.com/matiasinsaurralde/go-wasm3#memory-access

**Comment by matiasinsaurralde** [comment]
Some updates:
- Previous memory access approach was bad and implied copy using a Go helper (`C.GoBytes`) (so memory was read-only). Now there's direct access using the same approach that Wasmer uses for its Go extension. It's possible to read/write without issues and it's exposed as a Go `[]byte`:
```go
// Write
runtime.Memory()[pos] = byte(0)
// Read
runtime.Memory()[pos]
// Get length
len(runtime.Memory())
```
- Initialization was simplified and currently looks like this. Have added a flag to link the WASI modules. `Destroy` frees the runtime and environment:
```go
runtime = wasm3.NewRuntime(&wasm3.Config{
  Environment: wasm3.NewEnvironment(),
  StackSize:   1024 * 1024,
  EnableWASI:  true,
})
defer runtime.Destroy()
```
- Functions can be located with this syntax, they return a `func` and can be called directly like these. Argument length is dynamic. When the function doesn't exist we throw a proper Go `error`.
```go
allocateFn, err = runtime.FindFunction("wasm_allocate")
val, err := allocateFn(16)
if err != nil {
  panic(err)
}
fmt.Println(val)
```
- When `Call` throws an error, it returns a Go error too, using a callback, specified [here](https://github.com/matiasinsaurralde/go-wasm3/blob/master/error.go#L13). `lastError` holds the last error message and there's a function to get it (`wavm3.LastErrorString()`):
```go
package wasm3

/*
#include "go-wasm3.h"
*/
import "C"

var(
	lastError string
)

//export set_error
func set_error(str ResultT) {
	lastError = C.GoString(str)
}
```
- Missing functionality: allow a Go function to be called from the WASM side.
- Some examples with tests and benchmarks added:

[`sum` (the classic program)](https://github.com/matiasinsaurralde/go-wasm3/tree/master/examples/sum)
[`cstring` (reconstructing  a C string from WASM memory)](https://github.com/matiasinsaurralde/go-wasm3/tree/master/examples/cstring)
[`boa` (Boa is a JS interpreter built in Rust, this sample loads a WASM version of it, calls the interpreter and gets the output back)](https://github.com/matiasinsaurralde/go-wasm3/tree/master/examples/boa)
[`libxml` (loads `libxml2` and validates a XML file using a XSD)](https://github.com/matiasinsaurralde/go-wasm3/tree/master/examples/libxml).

**Comment by vshymanskyy** [comment]
Thanks @matiasinsaurralde , this os now featured on the top-level Readme of wasm3. Great job, and really helpful!

**Comment by vshymanskyy** [comment]
@matiasinsaurralde FYI the project now uses CMake library structure.

**Comment by matiasinsaurralde** [comment]
@vshymanskyy Thanks, will check it out!
