### ISSUE TITLE
How to export function?

### ISSUE THREAD

**Issue by weiqingtangx** [wasm3/wasm3#384]
Hi there,
I want to embed wasm3 in my iOS App to run a render engine, and I want to link some functions to wasm3 container, as below:
```
m3ApiRawFunction(m3_wasi_clear_rect) {
    m3ApiGetArg   (float, x)
    m3ApiGetArg   (float, y)
    m3ApiGetArg   (float, width)
    m3ApiGetArg   (float, height)
    
    CanvasContext* context = (CanvasContext*)(_ctx->userdata);
    context->ClearRect(x, y, width, height);
    m3ApiSuccess();
}

M3Result  m3_LinkCanvas  (IM3Module module, CanvasContext *context)
{
    M3Result result = m3Err_none;
    const char* canvas = "canvas"; // Here I tried const char* canvas = "*', not working
_   (SuppressLookupFailure (m3_LinkRawFunctionEx (module, canvas, "clearRect", "v(ffff)", &m3_wasi_clear_rect, context)));
_catch:
    return result;
}

//call m3_LinkCanvas somewhere 
```

And, I export the clearRect function in this way. But, I received an error: ```missing imported function``` in my App. My question is how to right declare the clearRect function in .cpp?
```
extern "C" void clearRect(float, float, float, float);

//call clearRect somewhere 
```
Thanks.

**Comment by weiqingtangx** [comment]
```
M3Result  m3_LinkCanvas  (IM3Module module, CanvasContext *context)
{
    M3Result result = m3Err_none;
    const char* canvas = "*"; 
_   (SuppressLookupFailure (m3_LinkRawFunctionEx (module, canvas, "clearRect", "v(ffff)", &m3_wasi_clear_rect, context)));
_catch:
    return result;
}
```
I figure out this problem.

**Comment by sfranzyshen** [comment]
> M3Result  m3_LinkCanvas  (IM3Module module, CanvasContext *context)
> {
>     M3Result result = m3Err_none;
>     const char* canvas = "canvas"; // Here I tried const char* canvas = "*', not working
> _   (SuppressLookupFailure (m3_LinkRawFunctionEx (module, canvas, "clearRect", "v(ffff)", &m3_wasi_clear_rect, context)));
> _catch:
>     return result;
> }

Looks like the fix was posted in the final response ...
>     const char* canvas = "canvas"; // Here I tried const char* canvas = "*', not working
