### ISSUE TITLE
Why scanf in C is not working in wasm3 after compilation to wasm?

### ISSUE THREAD

**Issue by YeeTone** [wasm3/wasm3#395]
I have tried using EMCC as compiler to compile the following C program to wasm and execute:
```C
#include <stdio.h>

int main(){
    printf("start...\n");
    int val = 123;
    scanf("%d",&val);
    printf("val: %d\n", val);
    return 0;
}
```
However, I cannot input any character as the scanf function defined in C library. I also tried the process in WAVM and the input works. Could anyone explain this inconsistency in wasm3?

**Comment by vshymanskyy** [comment]
You should compile it as a WASI module. Wasm3 does not provide any Emscripten bindings.

**Comment by YeeTone** [comment]
Thanks.
