### ISSUE TITLE
[question]Documents of memory management model of wasm3 ?

### ISSUE THREAD

**Issue by zwlaka** [wasm3/wasm3#398]
Hi!
Thank you very much for the great work!
I'm trying to learn some details about how a wasm VM works and I'm quite interested in the memory management of wasm3. 
I found that there are some subtle designs like block stack frame which confused me when i was reading the source code. I wonder whether there are documents that explain it in detail?

**Comment by vshymanskyy** [comment]
There are no such docs, and the implementation is subject to change
