### ISSUE TITLE
Run CoreMark

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#4]
Bring `wasm3` to the level where it can run CoreMark, so we have more reliable numbers of it's performance.
In general we need to:
- [x] Build **CoreMark** to WASM
- [x] Benchmark some popular wasm runtimes using CoreMark
- [x] Implement the needed imported functions for `wasi` or `emscripten` interfaces
- [ ] Improve implementation (mostly by running spec tests and fixing inconsistencies)

**Comment by kripken** [comment]
I built CoreMark to wasm now, I'm attaching the build in case it's useful.
[coremark.wasm.zip](https://github.com/vshymanskyy/wasm3/files/3848659/coremark.wasm.zip)

(I built it with `emcc -O3 -I. -Ilinux/ -DFLAGS_STR -o coremark.js core_list_join.c core_main.c core_matrix.c core_state.c core_util.c linux/core_portme.c -DPERFORMANCE_RUN=1 -DITERATIONS=1 -s STANDALONE_WASM` with emscripten 1.39.2 + a local patch for the time function, that I'll open a PR for later.)

**Comment by vshymanskyy** [comment]
@kripken Thanks much! Interesting thing, I didn't need any patches to do this:
https://github.com/vshymanskyy/wasm3/tree/master/test/benchmark/coremark - see the README here

**Comment by vshymanskyy** [comment]
It looks like `wasm3` is a few miles away from executing this ;)
Anyway I'll be fixing spec tests and then trying this out from time to time.
Eventually we'll get there.

**Comment by kripken** [comment]
Oh cool, I didn't see the README :)

Reading it now, I think the `SIDE_MODULE` build is probably not a good idea, as it's a dynamic library, so it's relocatable - that adds overhead to things.

Also, `-flto` is used in the wasi build I see, but you need it in emscripten too (we're going to simplify the LTO flags eventually...).

**Comment by kripken** [comment]
Oh, and the build I attached is a "standalone" one - where emscripten emits a wasm file that uses wasi and can run in wasi VMs, without any JS. That mode required a local patch as I just now noticed a missing wasi method.

**Comment by vshymanskyy** [comment]
Having some good progress on #7 , I'd say we're pretty close to running CoreMark.

But there are (at least) a few missing things:
- [ ] https://github.com/wasm3/wasm3/blob/e061b68dc865a0def6d343deed836fee8e45bc26/source/m3_compile.c#L923
- [ ] https://github.com/wasm3/wasm3/blob/e061b68dc865a0def6d343deed836fee8e45bc26/source/m3_compile.c#L1158

**Comment by vshymanskyy** [comment]
We're now able to run CoreMark! :tada:
There still some major things that need to be fixed (branching, some floating point operations, etc.).
I think we can close this ticket.
