### ISSUE TITLE
preserving local: N to slot: N, m3NotImplemented

### ISSUE THREAD

**Issue by kgdev** [wasm3/wasm3#40]
In which situation we need this and why it's not implemented yet?

**Comment by vshymanskyy** [comment]
@soundandform I think I have hit this a few times already, when working on self-hosting.

**Comment by kgdev** [comment]
Anyway I can help on this?

**Comment by soundandform** [comment]
I can fix. I had been waiting for this case to come up in an actual .wasm file.

**Comment by kgdev** [comment]
```
(module
  (type (func))
  (func (type 0)
    (local i32)
      local.get 0
      block
        i32.const 0
        local.set 0
      end
      drop
    )
    (memory 1)
)
```

**Comment by soundandform** [comment]
Hah. Thanks. Yeah, a contrived wasm file was the runner up option :)

**Comment by kgdev** [comment]
The sample actually comes from a real wasm from a game :)

**Comment by kgdev** [comment]
It seems that we have to insert the "preserve" local operation before the previous block. What's the best way to do that?

**Comment by kgdev** [comment]
Or just preserve all locals just before a block?

**Comment by kgdev** [comment]
https://github.com/wasm3/wasm3/pull/42

**Comment by soundandform** [comment]
@kgdev I haven't addressed loop and if yet which is why I said it was "partial."

**Comment by vshymanskyy** [comment]
I believe this is fixed now. @kgdev please verify

**Comment by kgdev** [comment]
![image](https://user-images.githubusercontent.com/6348456/72677650-aa6ff680-3ad9-11ea-9dca-6876161c82dc.png)

Both "local.get $1" would be replaced to a slot, saying 40. So slot 40 is referenced twice. When deallocating slot 40, we need to keep a count instead of 1 or 0.

**Comment by vshymanskyy** [comment]
Should be OK now. Please report it still have problems with this
