### ISSUE TITLE
Implement stack access API

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#41]
We need to come up with some stack access API, as currently we can only get function results by tampering with the stack directly. I.e. this has to be revised:
https://github.com/wasm3/wasm3/blob/99bdcabdcd06c278d3ffd290348effb2f7b8fbbd/platforms/arduino/src/main.cpp#L48-L55

Please comment if you have any suggestions on the API.

**Comment by sletz** [comment]
Maybe using an union to decribe the possible result types ? Like in [wasmer](https://github.com/wasmerio/wasmer/), see https://github.com/wasmerio/wasmer/blob/master/lib/runtime-c-api/wasmer.h

```
typedef union {
  int32_t I32;
  int64_t I64;
  float F32;
  double F64;
} wasmer_value;

typedef struct {
  wasmer_value_tag tag;
  wasmer_value value;
} wasmer_value_t;
```

**Comment by igrr** [comment]
Another option is to extend m3_CallWithArgs to accept the destination for saving the return value:

```c++
M3Result  m3_CallWithArgs  (IM3Function i_function, uint32_t i_argc, const char * const * i_argv, void* out_result, size_t out_result_size)
```

Internally this would check that `out_result_size` matches the function return type, and `memcpy` from the stack to `out_result`.

The downside compared to tagged enum approach is that the application needs to know the exact type of the return value. However this is also a problem for function arguments. I think adding another API to query function signature would help in both cases.

**Comment by igrr** [comment]
I'd like to extend this feature request to include function invocation.

Currently if we want to invoke a WASM function, we need to pass arguments as strings. The arguments are then converted to the integral types inside m3_CallWithArgs.

In the case when we already have the int/float/pointer arguments, it would be more efficient to place them onto the stack and then invoke the required function.

**Comment by vshymanskyy** [comment]
@igrr thanks it's a very good idea.
We will create a separate branch for developing several API-breaking features.

**Comment by vshymanskyy** [comment]
API status:
- [x] Query function signature: `m3_GetArgCount`, `m3_GetRetCount`, `m3_GetArgType`, `m3_GetRetType`
- [x] Call function using argument pointers, not strings: `m3_Call`
- [x] Call function using variadic arguments: `m3_CallVariadic`, `m3_CallWithArgs`
- [ ] Get function results

Please comment if you have any preferences/ideas on `Get function results API`

**Comment by vshymanskyy** [comment]
My current idea is to have
```cpp
    M3Result            m3_GetResults               (IM3Function i_function, uint32_t retc, const void * o_retptrs[]);
```
Which can be called after any of the `m3_Call*` functions.
It can check if the function was previously called internally.

**Comment by arrisde** [comment]
Great to see the progress on this! I assume by returning an array from `m3_GetResults` you are preparing for [multi-value](https://github.com/WebAssembly/multi-value) support? 
Since there are still lots of WASM modules in the wild returning single values, it might be a good idea to also offer typed single-value APIs as shortcut alternatives, e.g. 
```c
M3Result m3_GetResultI32 (IM3Function i_function, uint32_t * retptr);
M3Result m3_GetResultI64 (IM3Function i_function, uint64_t * retptr);
...
```
This would improve ergonomics when working with single-valued functions (no heap allocation or casting necessary).

**Comment by vshymanskyy** [comment]
@arrisde how about a variadic variant:
```
M3Result m3_VGetResults(IM3Function i_function, int ret_count, ...);
...
float ret0; u64 ret1;
m3_VGetResults(f, 2, &ret0, &ret1)
```

**Comment by igrr** [comment]
I'd advise against the variadic option, as there is no way to implement type checking for it. If WASM code is changed and the function signature becomes different, there will be no compile error that would warn the user that the variable type doesn't match WASM return type. Having simple m3_GetResultI32, m3_GetResultU64, m3_GetResultF32, etc functions is the most reliable option.

That said, it is pretty easy to extend the existing C++ wrapper with such a variadic call function which would do type checking.

**Comment by arrisde** [comment]
The variadic option sure looks convenient, but in my experience variadic can be a pain when invoked through FFI from other languages.

**Comment by vshymanskyy** [comment]
Yes, this also bothers me a lot. In this sense, there's also no need to pass the `argc` to a variadic function, as signature of a function is known. So I'll probably remove `argc` checks. Anyway I think variadic is convenient in those cases when you call just a single (and known) function, and it's not the only way to call a function or get the results. For FFI/C++ wrapper, you can use generic `Call`, `GetResults`.

**Comment by vshymanskyy** [comment]
@igrr Also, if we want a safe API, I'd go with a `tagged union` approach. This would achieve 2 things:
- Allow us to validate each argument type
- Ensure adequate space is allocated for each result. The caller won't have to bother.

Anyway, nothing restricts us from exposing all of these methods.

**Comment by igrr** [comment]
@vshymanskyy sure, tagged union is a nice approach as well.

Do you need any help fixing the C++ wrapper after these changes?
