### ISSUE TITLE
Examples for loading .wasm files and executing functions

### ISSUE THREAD

**Issue by atecey** [wasm3/wasm3#413]
Are there any examples of loading and running a .wasm file? 

I've managed to parse/load module and find the function but cannot find anything on getting the function to execute successfully without throwing "missing imported function".

N.B. my .wasm file is just a simple rust function and print statement ATM (tried a few different things to export the function) compiled with wasm32-wasi targets.

Any pointers would be much appreciated. Thanks

**Comment by FGasper** [comment]
@vshymanskyy: Have you considered enabling the GitHub Discussions feature for this repository? It would seem a more appropriate place for these kinds of “how-to-use” threads.

@atecey: Did you enable wasm3’s WASI? Did you supply all other imports that your WASM file may expect? Try `wasmer inspect` on it to see what all you need to provide in order for your WASM program to run.

**Comment by FGasper** [comment]
@atecey Look at m3_api_wasi.h for wasm3’s WASI controls.

**Comment by vshymanskyy** [comment]
Currently, we have a Discord channel: https://discord.com/invite/qmZjgnd

**Comment by sfranzyshen** [comment]
> Currently, we have a Discord channel: https://discord.com/invite/qmZjgnd
![Discord](https://github.com/wasm3/wasm3/assets/5503445/d383206b-a580-41c4-9eb1-b176e17e4305)
Not working for me :(
