### ISSUE TITLE
More details on supported platforms

### ISSUE THREAD

**Issue by Tudyx** [wasm3/wasm3#414]
Thanks for your work! In the doc it's written that Windows is supported, do you know to what extent?
Can I run it in Windows XP or Windows Vista or I must use recent OS?

**Comment by vshymanskyy** [comment]
Wasm3 relies on `libuv` for WASI implementation by default, so it's [limited to `Windows 8`](https://github.com/libuv/libuv/blob/v1.x/SUPPORTED_PLATFORMS.md) and higher.
But, when compiled without WASI support it can run on **any** Windows or even DOS.
