### ISSUE TITLE
What does IsStackPolymorphic actually mean?

### ISSUE THREAD

**Issue by kgdev** [wasm3/wasm3#43]
It seems that it's used to defer the unwind of stack. Could anyone elaborate more on this?

**Comment by soundandform** [comment]
See the Wasm spec: https://webassembly.github.io/spec/

**Comment by vshymanskyy** [comment]
@kgdev please close this ticket if this answers your question.

**Comment by vshymanskyy** [comment]
Please continue discussion  if needed.
