### ISSUE TITLE
How to 'import' native c++ functions?

### ISSUE THREAD

**Issue by blitz-research** [wasm3/wasm3#437]
Is it possible to interpret a wasm app inside a c++ app, and provide the interpreter a set of native/extern functions that the interpreted wasm code can import and call?

I've already got something like this going in wasmer using the c-api, example here:

https://github.com/wasmerio/wasmer/tree/master/lib/c-api

Basically, I want to do the same things as this but have it interpreted instead of JIT-ted, preferably using wasm3 as it sounds like it's lightweight and FAST!

Note the wasmer code above uses a 'wasm.h' C API which seems to be a loose standard of sorts shared by a few wasm tools, eg: wasmtime and wasmer, and I was hoping wasm3 might have something similar but haven't found anything so far.

Also, sorry if this isn't really an 'issue' - is there a more newbie place to ask questions?

Bye,
Mark

**Comment by bonifaido** [comment]
Hi @blitz-research,

yes this is totally possible, wasm3 only supports C function bindings, so if you wrap your C++ functions you are free to do that. I suggest t analyze https://github.com/wasm3/wasm3/blob/main/source/m3_api_libc.c#L208 for more details.
