### ISSUE TITLE
Run Wasm3 android examples

### ISSUE THREAD

**Issue by AndradeMaicon** [wasm3/wasm3#438]
Hi, recently started to study webassembly and after I hear about Wasm3 I tried to run wasm files into Android following the example available inside this repository ``/platforms/android``.

So after cloning and building the Android project, I had success to run the coremark file as an example, but when I try to run another file as ``fib32.wasm.h`` in ``app/src/main/cpp/m3/extra`` I received the following error: "Fatal: m3_FindFunction: function lookup failed"

Could you help me understand my error? Do you have another example with a different wasm function that I can see?

**Comment by creator-ms** [comment]
I run it on windows, there's a file app/src/main/cpp/m3, which may be a symbolic link to the source folder,
if you cannot create symbolic link , just replace the file with a directory named 'm3' and copy the source there

not sure this is the best way , you can also create a symbolic link from powershell with admin right

**Comment by AndradeMaicon** [comment]
> I run it on windows, there's a file app/src/main/cpp/m3, which may be a symbolic link to the source folder, if you cannot create symbolic link , just replace the file with a directory named 'm3' and copy the source there
> 
> not sure this is the best way , you can also create a symbolic link from powershell with admin right

Thanks for help me.
