### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by erxiaozhou** [wasm3/wasm3#441]
### Current State
Crash
```
Segmentation fault (core dumped)
```

## Environment
- Code Version: git commit id 772f8f4648fcba75f77f894a6050db121e7651a2
- Hardware Architecture: x86\_64 
- Operating system: Ubuntu 20.04

## Steps to Reproduce

commands to build:
```
export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
rm -rf build
mkdir build
cd build
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug .. 
ninja
```
[i32.add_1034_4_1682980265279482.zip](https://github.com/wasm3/wasm3/files/12323846/i32.add_1034_4_1682980265279482.zip)

```
build/wasm3 --func to_test i32.add_1034_4_1682980265279482.wasm
```

**Comment by vshymanskyy** [comment]
unexpected opcode: 0xc5
