### ISSUE TITLE
Wasm3 doesn't work

### ISSUE THREAD

**Issue by 702fbtngus** [wasm3/wasm3#459]
Hello. I downloaded the [executable wasm3 file](https://github.com/wasm3/wasm3/releases/download/v0.5.0/wasm3-linux-x64.elf), and it doesn't work as below.

```
$ ./wasm3 --repl fac.0.wasm
wasm3> :invoke fac-rec 3
Illegal instruction (core dumped)
```
fac.0.wasm is made from below .wast file:
```
(module
  ;; Recursive factorial
  (func (export "fac-rec") (param i64) (result i64)
    (if (result i64) (i64.eq (local.get 0) (i64.const 0))
      (then (i64.const 1))
      (else
        (i64.mul (local.get 0) (call 0 (i64.sub (local.get 0) (i64.const 1))))
      )
    )
  )
)
```

Just in case my CPU is the problem, it is Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz.

**Comment by vshymanskyy** [comment]
You should build wasm3 for your machine
