### ISSUE TITLE
Tail call optimization (TCO) is not supported in ARM?

### ISSUE THREAD

**Issue by kgdev** [wasm3/wasm3#47]
It seems that wasm3 runs quite slow in iOS. Anyone has similar cases?

**Comment by vshymanskyy** [comment]
Tail recursion is supported on ARM (starting with Cortex M3), but maybe we need to check what exactly is produced by iOS toolchain.

**Comment by vshymanskyy** [comment]
@kgdev are you sure you're running the Release build?

**Comment by vshymanskyy** [comment]
@kgdev on iPhone 8 and release build:
![image](https://user-images.githubusercontent.com/1506708/72272407-3ba22180-3631-11ea-8bbb-73a431052e18.png)

Which looks like a pretty good result.

**Comment by vshymanskyy** [comment]
I added some docs to clarify that `Release` build needs to be selected manually: https://github.com/wasm3/wasm3/blob/master/platforms/ios/README.md

**Comment by kgdev** [comment]
Thanks. We used the "Debug" build. After switching to Release build, it works great.

We fixed some issues and added some utility methods when we're trying to run a WEBGL game using wasm3. We will try to make some clean PRs soon or later.

**Comment by vshymanskyy** [comment]
Cool. Glad that helped! Be sure to check out the latest version ;)
