### ISSUE TITLE
Could i32, f32 occupy only 4 bytes on wasm stack?

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#5]
Most operations "know" exactly which type they are consuming. Notable exceptions are:
- Drop
- Select

According to [this comment](https://github.com/bytecodealliance/wasm-micro-runtime/issues/19#issuecomment-493820235), we can deduce the type during compile time.

**Comment by vshymanskyy** [comment]
I'm not sure if all of the platforms will handle 4-byte-aligned access to 64-bit values (and the performance hit associated with it). Whatever we do here, it would be good to have a flag to enable/disable it.

**Comment by soundandform** [comment]
I was planning on 8 byte aligning 64-bit values.

**Comment by soundandform** [comment]
Now implemented.  Selectable with d_m3Use32BitSlots in m3_config.h (true by default).

**Comment by vshymanskyy** [comment]
Great news @soundandform. Will put it to work!
