### ISSUE TITLE
Improve performance further (perform profiling, etc)

### ISSUE THREAD

**Issue by vshymanskyy** [wasm3/wasm3#50]
Wasm3 is fast, but we didn't even get to profiling yet.

As noted by @dstogov:
> Comparing wasm3 performance with PHP and converting this test to PHP... Actually, php master branch, compiled by GCC, with opcache/optimizer enabled (without JIT) is a bit (~15%) faster. I'm a bit surprised, because our VMs achieve very similar VM assembler code (by different ways), WASM code and data are simpler to interpret, and you made additional optimization for accumulator register. For some reason, wasm3 suffers from branch miss-prediction (more than 10 time more misses than PHP) and cache misses (almost 100 times more L1 DCache misses). Measured with Linux perf stat.
$ perf record -e L1-dcache-load-misses ./wasm3 mandel.wasm
$ perf report -n
It looks like, your virtual code segment evicted from CPU cache too often.
Fixing this, should significantly improve performance.
However, this also may be related to bad indirect branch prediction and speculative execution.

If you have any other ideas on how to improve performance, please comment here.

**Comment by soundandform** [comment]
Was there any note about what microarchitecture was perf'ed?  I've found that this is a vital piece of information when discussing cache/branch prediction performance.

**Comment by vshymanskyy** [comment]
@dstogov , please elaborate if possible

**Comment by dstogov** [comment]
It was Sandy Bridge i5-2520M

**Comment by soundandform** [comment]
Thanks!  I've tested a previous iteration of my interpreter design on Sandy Bridge.  It wasn't exactly like Wasm3, but close enough.  Performance was not great (4-5X slower).  Like you're seeing, it seems like branch prediction totally fails. As a quick experiment, I was able to improve performance dramatically by duplicating the most common operations multiple times and round-robin emitting the various versions.  This gave the branch predictor much better (program counter) information.  More recent microarchitectures have a more complex branch predictor.   Sandy Bridge is now about 10 years old (8 intel generations), so it might be hard to justify optimization for this architecture.

**Comment by dstogov** [comment]
@soundandform yeah, Sandy Bridge is an old and shouldn't be the most important targeted for optimization. I just saw a huge difference with PHP and let you know. I'm not sure how newer CPU will perform, but most probably, branch predictor won't be able to improve unpredictable indirect branches anyway.

I suppose, one of the main source of miss-prediction is op_SetSlot instructions family. It is possible to improve the situation combining them with the previous instruction. e.g. op_i32_Add_ss[_s].

**Comment by soundandform** [comment]
@dstogov Have you ever used the Intel VTune profiler? I'm curious if that would provide any insight.   I haven't used `perf` too much.  It gives you interesting information, but nothing really actionable from what I recall. 

I've been toying around with this basic interpreter design in my spare time for a few years.  This wasm3 project is maybe the 3rd or 4th iteration. In a previous design, I did have "slot destination" permutations of every operation.  (This obviously starts to blow up the operation-space quite a bit -- totally reasonable in a desktop environment, but not embedded friendly.)  In the end, I think the current implementation has a tad higher performance (on x86).  If I learned anything from this project, it's: it is impossible to make any guess about how a modern CPU is going to perform.  It's a complex and mostly opaque black box.  The only solution has been to try things and see what happens.  And, my predictions have usually been wrong.

**Comment by dstogov** [comment]
I worked with Intel VTune in the past. It maight provide more accurate profiles, but didsn't give any useful insight. The only useful suggestion from Intel experts was using "Top-Down performance analysis methodology" (e.g. https://www.researchgate.net/publication/269302126_A_Top-Down_method_for_performance_analysis_and_counters_architecture ). Following it, I understood that the things are even worse, because CPUs perform a lot of useless speculative work that later discarded.

You may also try "valgrind --tool=callgrind" + kcachegrind to run on emulated CPU and see where you have cache misses. Unfortunately, I don't know tools, that may explain, why some data was evicted from CPU cache. The best strategy - use less data grouped together.

**Comment by dstogov** [comment]
I've run wasm under valgrind/callgrind on weekend, and it showed enormous amount of L1 data read cache misses (300 times more than PHP). This is not related to branch miss-prediction or speculative execution.
Looks like very bad memory access patterns. May be your local data is allocated not in continuous memory region(s), but spread randomly. Also, arena-like allocator for virtual code and meta-data may help.

I hope, you should have a good potential for performance improvement :)

**Comment by soundandform** [comment]
investigate musttail once available.  https://blog.reverberate.org/2021/04/21/musttail-efficient-interpreters.html

**Comment by vshymanskyy** [comment]
`musttail` is implemented (and more widely available in compilers now), Tail Calls are optimized, and with the latest optimizations we're getting +19.1% geomean speedup:

metric | main | optz | ratio | rounds
-- | -- | -- | -- | --
stream-scale | 3,203 | 5,078 | 1.577× | 10/10
mandel | 0.277 | 0.369 | 1.330× | 10/10
brotli | 0.596 | 0.746 | 1.281× | 10/10
stream-triad | 3,356 | 4,096 | 1.228× | 10/10
stream-add | 3,530 | 4,306 | 1.206× | 10/10
coremark | 3,381 | 3,970 | 1.179× | 10/10
smallpt | 0.488 | 0.564 | 1.161× | 10/10
c-ray | 479.0 | 541.3 | 1.134× | 10/10
stream-copy | 3,326 | 3,545 | 1.060× | 10/10
selfhost-fib |   |   | 1.035 | 7/10 — noise
mal-fib |   |   | 1.010 | 7/10 — noise

Associated optimizations:
- `fold/fuse` +12.9% geomean, the bulk of CoreMark's and brotli's share
- `extended folding to f32/f64/i64 + all loads` +6.4% geomean, essentially all of mandel/c-ray/smallpt and much of STREAM
- `fold write-through + tee in register ` +7-8% on STREAM arithmetic specifically
- `preserve_none calling convention` ~neutral, kept as an enabler
