### ISSUE TITLE
How to Implement JS Functionality in Wasm3

### ISSUE THREAD

**Issue by peace737** [wasm3/wasm3#512]
javascript sample :

var memory = new WebAssembly.Memory({initial: 10, maximum: 100});

**Comment by tommie** [comment]
I'm not quite sure what you're asking. If it's about getting hold of Memory, you can use [`m3_GetMemory`](https://github.com/wasm3/wasm3/blob/79d412ea5fcf92f0efe658d52827a0e0a96ff442/source/wasm3.h#L216).

There is no way to import a Memory:

https://github.com/wasm3/wasm3/blob/79d412ea5fcf92f0efe658d52827a0e0a96ff442/source/m3_env.c#L390-L393
