### ISSUE TITLE
Readme misstyping ∼ 4..5x slower

### ISSUE THREAD

**Issue by flowHater** [wasm3/wasm3#52]
should be 
`∼ 4.5x slower`

**Comment by vshymanskyy** [comment]
I think it's correct, 4 to 5 times.. JITs usually display more dispersion in the results.

**Comment by flowHater** [comment]
So may be `∼ 4-5x slower`
`∼ 15.8x faster`
`∼ 4..5x slower`
`∼ 11.5x slower`

It seems to be a misstyping. Maybe it's not. But it seems.
