### ISSUE TITLE
calculation of numActiveCodePages is wrong.

### ISSUE THREAD

**Issue by kgdev** [wasm3/wasm3#54]
![image](https://user-images.githubusercontent.com/6348456/72487446-0243fe80-3849-11ea-9bf9-0c951f8c84a6.png)

The call could be nested. So numActiveCodePages should be added beforehand.

**Comment by soundandform** [comment]
thanks! should be fixed now.

**Comment by vshymanskyy** [comment]
On `smallpt-ex` test, I still get the assertion failure:
```log
cd test
../build-dbg/wasm3 ./benchmark/smallpt/smallpt-ex.wasm 4 64 > out.ppm
Rendering (4 spp)  0.00%
/home/vshymanskyy/_Projects/Wasm/wasm3/source/m3_env.c:793: ReleaseCodePage: Assertion `numOpen + numFull + env->numActiveCodePages == env->numCodePages' failed.
```

**Comment by vshymanskyy** [comment]
Seems good now
