### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wasm3/wasm3#55]
I would like to point out that an identifier like “[`__wasi_core_h`](https://github.com/wasm3/wasm3/blob/b1462d450ca367e39e4b2eb414f1520f73dfb7ab/source/extra/wasi_core.h#L11 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by vshymanskyy** [comment]
This file was copied directly from wasi libc.

**Comment by vshymanskyy** [comment]
There's quite a lot of reserved identifiers right now. They can be identified to some extent with this command:
```sh
grep -R " _" ./source
```
WASI-related stuff can't be easily fixed, but we're considering to switch to [uvwasi](https://github.com/cjihrig/uvwasi) for WASI implementation.

Let us know if any specific (and non-WASI) identifiers are causing problems for you, and we'll fix that,

**Comment by elfring** [comment]
Would you like to [recheck the tampering with the reserved name space](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers")?
