### ISSUE TITLE
Example interacting with hardware peripherals

### ISSUE THREAD

**Issue by beriberikix** [wasm3/wasm3#57]
All the platforms use the same fib32.wasm.h but I haven't found an example that interacts with the hardware peripherals like GPIO. Is that possible, even if with a bit of wasm<>C++ glue code? I could imagine something like [wasm-bindgen](https://rustwasm.github.io/docs/wasm-bindgen/) be helpful here, or Interface Types when that's ready. But for now blinking an LED would be great :)

**Comment by vshymanskyy** [comment]
Absolutely. This is very easy actually, I'll add an example soon.
In meantime, you can check out the ESP32 WASI example here: https://github.com/wasm3/wasm3/tree/master/platforms/esp32-idf-wasi

**Comment by vshymanskyy** [comment]
@beriberikix Also, is there a preferred platform, you'd like an example for? ;)

**Comment by vshymanskyy** [comment]
Also, Interface Types rely on  `multi-value` and `reference types` post-MVP features, which we hope to start working on soon

**Comment by beriberikix** [comment]
> check out the ESP32 WASI
Ah, neat! Somehow I missed it.

>  preferred platform
I'm giving a talk in a few weeks and would love to demo 1 or 2 common platforms. Arduino Uno and ESP32 are familiar to many, so either or both if its possible!

>  post-MVP features
Totally, we all hope for those specs to be ready soon.

**Comment by vshymanskyy** [comment]
Arduino Uno won't be possible with it's ~30Kb Flash, 2Kb of RAM.
But we have an example for ATmega1284 with 128Kb flash, 16Kb RAM (just for fun).
I'll create an example for ESP32/ESP8266 with Arduino Core.

**Comment by beriberikix** [comment]
Thank you! What hardware are you using for ATmega1284? Just an Microchip devboard or something else? I also have mega1284s & heaps of Bluepills to try if the demo is portable.

**Comment by vshymanskyy** [comment]
For ATmega1284, we used `Wicked Device WildFire V3`.
8-bit chips are not too WebAssembly-friendly anyway ;)

You can now find the example for ESP32 here:
https://github.com/wasm3/wasm3/tree/master/platforms/arduino_blink

Let me know if you have any questions/suggestions or need any assistance.

**Comment by vshymanskyy** [comment]
@beriberikix you can now find Rust and TinyGO app examples running on ESP32, in the same directory

**Comment by beriberikix** [comment]
Awesome! I'll try it tonight!

**Comment by vshymanskyy** [comment]
@beriberikix if everything goes well, I can publish Arduino/Particle/PlatformIO libraries in notime.

**Comment by vshymanskyy** [comment]
We have `AssemblyScript` example now as well. Thx @MaxGraey !

**Comment by vshymanskyy** [comment]
The example is now available as part of `Arduino/Particle/PIO` library here:
https://github.com/wasm3/wasm3-arduino

I've also started the library registration procedure for all of the environments. Should be available soon in the Library Manager.
Currently it's only usable on platforms with ~80 Kb of free RAM (due to 64K), but already working on a fix.

**Comment by vshymanskyy** [comment]
Blink example is now available for ESP32, ESP8266, MKR1000, TinyBLE, Teensy31, WildFireV3 devices. Closing this, but feel free to ask questions, if needed!

**Comment by vshymanskyy** [comment]
`BluePill` is also working now

**Comment by vshymanskyy** [comment]
PlatformIO library is published: https://platformio.org/lib/show/6973/Wasm3
Particle library is published: https://build.particle.io/libs/Wasm3/latest/tab/example/Wasm_Blink.ino
Arduino Library is pending review: https://github.com/arduino/Arduino/issues/9642

**Comment by vshymanskyy** [comment]
`AssemblyScript`, `Rust` and `TinyGo` examples were updated and polished.
