### ISSUE TITLE
Document configuration options

### ISSUE THREAD

**Issue by matiasinsaurralde** [wasm3/wasm3#60]
Hi, while working on #38 I did some experiments like building `libxml2` as a WASM module.
I'm not able to load it using the current `master` as it seems to trigger `typeListOverflow`. Not sure if this is temporary or something related to the specs.

If you want to try it out, you can grab `libxml2.wasm` from [here](https://github.com/matiasinsaurralde/wasm-libxml2). In the meantime I'm able to use the module by tweaking `d_m3MaxNumFunctionArgs` in `m3_config.h`:
```patch
index a10cf61..e5bd84d 100644
--- a/source/m3_config.h
+++ b/source/m3_config.h
@@ -11,7 +11,7 @@
 #include "m3_config_platforms.h"
 
 # ifndef d_m3MaxNumFunctionArgs
-#   define d_m3MaxNumFunctionArgs               16
+#   define d_m3MaxNumFunctionArgs               32
 # endif
 
 # ifndef d_m3CodePageAlignSize
```
Regards.

**Comment by vshymanskyy** [comment]
I think we just need to spend some time on documenting the configuration options ;)

**Comment by matiasinsaurralde** [comment]
> I think we just need to spend some time on documenting the configuration options ;)
Cool 👍

**Comment by matiasinsaurralde** [comment]
A helper to modify this type of options on runtime could be useful too. What are your thoughts?

**Comment by soundandform** [comment]
I just changed the default to 31.  I'll switch this to a dynamic array soon to get rid of this define altogether.

**Comment by matiasinsaurralde** [comment]
@soundandform Awesome, thanks!
