### ISSUE TITLE
In PreservedCopyTopSlot and Compile_SetGlobal, we should differentiate the cases for f64/f32/i64/i32

### ISSUE THREAD

**Issue by kgdev** [wasm3/wasm3#64]
![image](https://user-images.githubusercontent.com/6348456/72789717-349d9380-3c6f-11ea-9d48-905e95731100.png)
![image](https://user-images.githubusercontent.com/6348456/72789745-3cf5ce80-3c6f-11ea-940c-517f7f4c1d40.png)

In CopyTopSlot, we can just use op_CopySlot_64. op_CopySlot_32 is unnecessary.

**Comment by kgdev** [comment]
This bug is pretty true. A local.get with a local.set immediately after it for f32 would trigger this bug.

**Comment by soundandform** [comment]
Yep, definitely. Thanks for the report!  I just pushed a patch. Let me know if anything looks off.
