### ISSUE TITLE
getrandom(2) does not exist in Ubuntu 16.04

### ISSUE THREAD

**Issue by opless** [wasm3/wasm3#65]
In Ubuntu Xenial 16.04 it does not have /usr/include/sys (there is a /usr/include/linux/random.h, but no getrandom defined)

It appears in Bionic (18.04) however.

What is the minimum version of glibc is recommended?

Do you intend to support 16.04 ?

**Comment by vshymanskyy** [comment]
The fix should be really easy. just use another api available on your system.
As for supporting 16.04.. We're going to swap wasi imlenentation with a third-party library anyway.
