### ISSUE TITLE
m3_GetErrorInfo broken

### ISSUE THREAD

**Issue by soundandform** [wasm3/wasm3#67]
M3ErrorInfo originally used a fixed string array to simplify & avoid memory ownership issues. The pointer mechanism in use now is getting nullified  when m3_GetErrorInfo is called so no actual error information is show.

**Comment by soundandform** [comment]
@vshymanskyy What was the motivation for the change?  Pros are: The fully encapsulated struct avoided such free/modify-after-use issues, which = idiot-proof API. Also, connecting to external world isn't as simple: in C++, I need to wrap the struct in a class that makes a copy of the string.

**Comment by vshymanskyy** [comment]
@soundandform the main motivation was to make the error messagr buffer allocation optional (or under a flag)
