### ISSUE TITLE
why we need memcpy in d_m3Load? It seems pretty heavy.

### ISSUE THREAD

**Issue by kgdev** [wasm3/wasm3#68]

**Comment by kgdev** [comment]
![image](https://user-images.githubusercontent.com/6348456/72978303-2f784a00-3e11-11ea-93e3-438ab9eea9a0.png)

**Comment by kgdev** [comment]
replace them in load and store will boost the performance quite a lot.

**Comment by vshymanskyy** [comment]
@kgdev did you try this? Compilers are usually smart enough to deal with this.
This is here to support systems that cannot perform misaligned memory access.
