### ISSUE TITLE
What about a clang interpreter w/ the same performance characteristics as wasm3?

### ISSUE THREAD

**Issue by unicomp21** [wasm3/wasm3#75]
A very nice side effect would be having clang coroutines!

**Comment by vshymanskyy** [comment]
@unicomp21 please provide instructions on how to build and run benchmarks with this.
What project are you talking about?

**Comment by vshymanskyy** [comment]
@unicomp21 or are you suggesting to implement one? ;)

**Comment by unicomp21** [comment]
Actually what I really meant was an interpreter for llvm, clang generates llvm instructions.  Given llvm supports coroutines, this would be a pretty elegant way to get c++ coroutines on webassembly.

I'm suggesting to implement one.  This might be a good starting point.
https://llvm.org/docs/CommandGuide/lli.html

**Comment by vshymanskyy** [comment]
This is out of scope for this project, however I suggest you to look at VMIR: https://github.com/andoma/vmir
