### ISSUE TITLE
[ESP32] memory allocation failed in WASI example

### ISSUE THREAD

**Issue by Isigiel** [wasm3/wasm3#87]
When running the WASI example for ESP32 without changes it fails with
```
Wasm3 v0.4.6 on ESP32, build Feb  2 2020 15:12:40
Loading WebAssembly...
Fatal: m3_LoadModule: memory allocation failed
Elapsed: 10 ms

Done
```

I'd be glad for any hint as to why that is happening

**Comment by robinvanemden** [comment]
The WASI example needs an ESP32 module or board with PSRAM - so the example should work on, for instance, an [ESP32 WRover, but not on an ESP32 WRoom](https://docs.espressif.com/projects/esp-idf/en/latest/hw-reference/modules-and-boards.html). Maybe you are using an ESP32 without PSRAM?

**Comment by Isigiel** [comment]
Thanks for the fast answer @robinvanemden 
I'm not very deep into this, is there no way to run a WASI example on a chip without PSRAM then?
You where spot on btw, I have a WRoom version in front of me.

The plan was to run a meaningful benchmark and it seemed like WASI would give me the best shot at doing things that are not purely computational.

**Comment by robinvanemden** [comment]
> I'm not very deep into this, is there no way to run a WASI example on a chip without PSRAM then?
Currently, I don't think so - see also [this issue](https://github.com/wasm3/wasm3/issues/26#issuecomment-570618820).

**Comment by vshymanskyy** [comment]
Just added a note about this to the https://github.com/wasm3/wasm3/blob/master/platforms/esp32-idf-wasi/README.md
Sorry it wasn't there before..
@igrr actually is looking at this, but it may require more efforts (and not planned currently)

**Comment by vshymanskyy** [comment]
@Isigiel also you might want to join our [Discord channel](https://discord.gg/qmZjgnd) to discuss what you're going to achieve in general.

**Comment by vshymanskyy** [comment]
Closing this as it is documented now
