### ISSUE TITLE
Any chance to support AOT or JIT?

### ISSUE THREAD

**Issue by warvstar** [wasm3/wasm3#89]
Wamr has added jit and aot as optional modes, it would be a great feature for wasm3 I'd think too.

Any plans to support in the future?

**Comment by vshymanskyy** [comment]
No, there's (globally) no point in developing a new AOT solution.
This is already well developed and supported by many projects.
@warvstar I suggest you to read [Wasm3 motivation](https://github.com/wasm3/wasm3#motivation)

**Comment by vshymanskyy** [comment]
Also, why going `Source Language -> ... -> WASM -> Native code`, instead of `Source Language -> ... -> Native code` directly (with better performance)?

**Comment by MaxGraey** [comment]
Also there are already exists solutions like InNative (LLVM-based solution) and wasm2c (from wabt).

**Comment by warvstar** [comment]
Fair enough, I think this can be closed.
