### ISSUE TITLE
Errors compiling in a C++ context

### ISSUE THREAD

**Issue by sletz** [wasm3/wasm3#92]
Two new errors I've got compiling the C sources in a C++ project;

```
./source/m3_compile.c:2052:20: error: use of undeclared identifier 'min'; did you mean 'fmin'?
    numConstants = min (numConstants, d_m3MaxNumFunctionConstants);

./source/m3_env.c:299:28: error: use of undeclared identifier 'min'; did you mean 'fmin'?
            numPageBytes = min(numPageBytes, io_runtime->memoryLimit);
 ``` 

Not sure how to properly fix them, so reporting them here.

**Comment by igrr** [comment]
Sorry, this is probably resulting from https://github.com/wasm3/wasm3/commit/b0874355d790b732799c9798a2584cdab1b4b1c5.

Are you compiling these C source files with a C++ compiler?

**Comment by sletz** [comment]
Yes because I'm mixing the wasm C files with C++ and it is simplifying compilation. This is a need first requested some weeks ago and fixed on wasm3 side.  I still think this is desirable, and be should tested and maintained.

**Comment by igrr** [comment]
Hmm, okay. While in general I'd argue that compiling C source files with a C++ compiler is not necessarily a good idea (due to e.g. different handling of designated initializers and functions prototypes without arguments), in this particular case it might be easier to fix this, than to argue. I'll submit a PR.

**Comment by vshymanskyy** [comment]
@sletz should be fixed now.
Be sure to (at least) run spec test with your compiler configuration, as "Building as C++" is not officially supported by Wasm3
