### ISSUE TITLE
No details on missing imported functions

### ISSUE THREAD

**Issue by jedisct1** [wasm3/wasm3#94]
Hi there!

When an imported function is missing, the REPL simply outputs:

```text
Error: [Fatal] repl_call: missing imported function
Error: missing imported function ()
```

It would be super useful to know what exact imported function is missing.

**Comment by vshymanskyy** [comment]
This is duplicate of #67 . Will get to this soon!

**Comment by jedisct1** [comment]
Woops, sorry for having missed the original issue.

**Comment by vshymanskyy** [comment]
@jedisct1 it's OK. Sometimes it's hard to associate different issue descriptions and side-effects, even for core developers ;)

**Comment by cpeggg** [comment]
May I ask is there any way to import the function that is in another wasm file by given args to wasm3 like --import <xxx.wasm>?
