### ISSUE TITLE
Discussion: reference IoT/embedded board ideal for beginners

### ISSUE THREAD

**Issue by beriberikix** [wasm3/wasm3#96]
I recently demoed Wasm3 on an ESP32 at a conference. The audience mainly weren't folks who've experimented with hardware previously. Many asked, "what should I buy to start playing with Wasm on hardware?" I think it would be good to pick a go-to platform (chipset+devkit vendor) that we can recommend, build tutorials around, etc. 

For example, we could pick the [Espressif DevKit-C](https://www.espressif.com/en/products/hardware/esp32-devkitc/overview) since it's fairly official, but has sourcing quality issues. Alternatively, the [Feather Huzzah](https://www.adafruit.com/product/3619) is available more broadly and includes the rich Feather ecosystem. However both suffer from the Tensilica known issues. Nordic chips are great, their DKs are easy to get, as well as variants from Adafruit or Sparkfun. Or maybe something without any connectivity at all to reduce complexity.

I don't have a strong recommendation because everything has tradeoffs but it would definitely help getting new people started :)

**Comment by vshymanskyy** [comment]
@beriberikix The answer to this question (partially) is here: https://twitter.com/wasm3_engine/status/1226200807768502272

All of those devices are almost "equally good" at running wasm ;)

**Comment by vshymanskyy** [comment]
For absolute beginners, I suggest those devices that support Arduino API out of the box.

**Comment by vshymanskyy** [comment]
We have a compatibility table here: https://github.com/wasm3/wasm3/blob/master/docs/Hardware.md
But I can also compile a similar comparison table for a small set of recommended devices.
Would that help?

**Comment by beriberikix** [comment]
Other things I consider when recommending hardware to beginners is:

- Lots of hw resources, since they don't want worry about being efficient. Ex. M4 over M0.
- Readily available around the world from reputable vendors. Ex. Amazon (ideally) or Adafruit over Aliexpress
- Lots of help for the non-toolchain stuff, like project or working with sensors. learn.adafruit.com or instructables are great examples.

Personally I think having one or a few "recommended, happy path" devices (with when that's recommended) would be nice. Maybe a comparison table with a simple check mark for "recommended for beginners" could be sufficient?

**Comment by vshymanskyy** [comment]
Added some recommended devices here: https://github.com/wasm3/wasm3/blob/master/docs/Hardware.md#recommended-devices-ideal-for-beginners

**Comment by vshymanskyy** [comment]
Also added Adafruit CLUE, PyGamer, PyBadge boards
