### ISSUE TITLE
Building CoreMark

### ISSUE THREAD

**Issue by kripken** [wasm3/wasm3#98]
Hi!

I am adding [CoreMark to the emscripten benchmark suite](https://github.com/emscripten-core/emscripten/pull/10426) and noticed I get different results than yours - v8 is 1.5x slower than native, instead of 2.7x on [your data](https://github.com/wasm3/wasm3/blob/master/docs/Performance.md). The versions are different on the compiler and vm, so it might be just that, but it is a pretty big difference.

When comparing the raw iters/sec numbers I see a small difference on native (likely our differrent CPUs) in comparison to the wasm difference, which again suggests we are building differently.

One thought I had was whether optimizations are done during link, and not just during compile, which matters on wasm builds with emscripten a lot more than on native. Reading the CoreMark makefile I'm not sure if that happens or not. Is SEPARATE_COMPILE passed? (if so I think a single command does it all, which should be ok)

**Comment by vshymanskyy** [comment]
Hey, thanks for reporting. I now realized that we have an emscripten CoreMark build, but this was not used to produce the results (we used wasienv).
And I don't remember how this one produced ))
Let me build it once again and document the process.

**Comment by vshymanskyy** [comment]
CoreMark builds have been moved to a separate repo: https://github.com/wasm3/wasm3-coremark
